= Тихвин -- отдых в ленобласти с детьми и без

== Что-нибудь про историю города

Бла-бла

== Как добраться

Время в пути до Тихвина составит примерно 3,5 часа на общественном транспорте. Электричка от Московского вокзала отходит в выходные дни в 7:36 и прибывают в 11:20. Стоимость -- 562 рубля.

Есть ещё электричка от Финляндского вокзала в 15:46 по пятницам воскресеньям. Электричка проводит в пути 4 часа 9 минут и прибывает в Тихвин в 19:55. Стоимость -- 593 рубля.

От Обводного канала до Тихвина каждые 50 минут ездят автобусы. Автобусы проводят в пути примерно то же время, билет обойдётся в ту же сумму, примерно 600 рублей.

За 2,5 часа на автобусе можно добраться до Тихвина от ТРК "Невский" у метро "Улица Дыбенко". Только этот автобус довезёт вас только до памятника авиаторам ВОВ на окраине города.

На машине при идеальных условиях без пробок путь до города составит ровно 3 часа.

Мы пробовали ездить на автобусе и на машине. На машине значительно комфортнее, а вот автобусам доверять не приходится. На пути из Тихвина автобус сломался и мы были вынуждены добираться 100 км до дома на такси.

== Жильё

Искать жильё в Тихвине лучше всего на онлайн-площадках по объявлениям от частных лиц. Средняя стоимость квартиры за сутки -- 1500-2000 рублей. Оптимально искать жильё в туристическом центре города: пятый, шестой и седьмой микрорайоны. В этом радиусе расположено большая часть интересных для туриста мест, например, главная достопримечательность города -- Тихвинский Богородичный Успенский Мужской Монастырь.

В этом году мы с женой нашли однокомнатную квартиру в 6 микрорайоне между улицами Красноармейская, Победы и Карла Маркса. Это идеальное расположение, так как позволяет быстро дойти пешком почти до любой части города, нужно только выйти на основную городскую улицу -- Карла Маркса.

Это наш второй визит в "город добра и благополучия", прошлый был 5 лет назад, тогда мы останавливались в 4 микрорайоне. Этот микрорайон расположен ближе всего к городской администрации, но застроен бывшими общежитиями и едва ли комфортен для проживания. Летом из открытых окон соседних домов доносилась очень громкая музыка, что сильно мешало комфортному пребыванию.

== Что посетить в городе

В небольшом Тихвине есть всё необходимое для приятного отдыха. основная достопримечательность -- Тихвинский Богородичный Успенский Мужской Монастырь.

=== Монастырь

Монастырь был основан по указу Ивана Грозного 10 февраля 1560 года. Главная монастырская реликвия -- чудотворная Тихвинская икона Божией Матери. По преданию эта икона раньше располагалась в городе Старая Русса на протяжении 200 лет. Когда в древности Тихвин и Старая Русса переживали голодные времена, одному мужчине было явлено послание свыше. Видение говорило о том, что  голод прекратится, если икону перенести из Старой Руссы в Тихвин, голод прекратится. Тогда в Старую Руссу перенесли список со тихвинской иконы, а оригинал перенесли в Успенский монастырь, и голод действительно прекратился.

Необязательно быть верующим, чтобы получить удовольствие от пребывания в монастыре. Кто угодно может полюбоваться звонницей Тихвинского монастыря. Изначально звонница была отстроена 1600 году, она несколько раз страдала от огня и взрывов, была уничтожена, в 1960-е годы была реконструирована, а в 2020 отреставрирована.

Также в стенах монастыря располагается Тихвинский краеведческий музей, вмещающий 36 тысяч экспонатов, рассказывающих об истории монастыря, Тихвинской иконы, археологии, этнографии, первой мировой войне и быте города.

=== дом-музей Римского-Корсакова

Ещё один важный для города музей -- дом-музей Римского-Корсакова, расположенный на противоположном от монастыря берегу реки Тихвинка. После утраты дома-музея в Псковской области важность дома-музея на родине Николая Андреевича Римского-Корсакова возросла ещё больше.

Это настоящий родной дом семьи Римских-Корсаковых, в 1801 году его построил дед композитора. Дом сохранился очень хорошо для деревянной архитектуры: оригинальные лепные карнизы, двери, печи, полы.

Музей -- это настоящее окно в жизнь семьи композитора, здесь можно увидеть их личные вещи, мебель, музыкальные инструменты и нотные тетради с автографами композитора. В доме хранятся даже личные вещи композитора из детства: детская одежда, перчатки, ленточка с отметками роста Ники Римского-Корсакова. Необязательно бронировать экскурсию, можно пройтись по дому самостоятельно, подняться на чердак и прогуляться по внутреннему дворику.

=== Тихвинский шлюз

Ещё одна достопримечательность в окрестностях монастыря -- тихвинский шлюз. Шлюз -- это восстановленная часть тихвинской водной системы, соединявшей Волгу с Балтийским морем. Длина Тихвинской водной системы составляла 924 километра, её активно использовали с 1811 года. К сожалению, до наших дней из 62 шлюзов не дошёл ни один. Часть шлюза рядом монастырём была разрушена паводком в2005 и восстановлена в 2014 году в соответствии с историческим обликом.

=== Еда

В городе есть несколько неплохих ресторанов и кофеен с вкусным кофе. При первом посещении местных ресторанов может показаться, что они все забронированы на мероприятие, но на самом деле -- это одна из местных особенностей. На всех столах в ресторанах в Тихвине принято красиво ставить салфетки и раскладывать приборы рядом с тарелками. Когда посетители садятся за стол, салфетки убирают и приносят новые. Неподготовленному посетителю кажется, что вот-вот нагрянет какая-нибудь свадьба, но это просто забавная традиция.

Отмечу несколько интересных заведений:

"Кофе берри", 1-й микрорайон, 43. Кофейня на северной окраине города, дальше только стадион "Кировец" и Фишева гора. Кофейня может предложить вкусный кофе в ассортименте, десерты, удобные столики и интересный интерьер с множеством мелких деталей. Здесь также можно купить открытки от местного художника и почитать книги. Отличное место для уютных посиделок. Кроме кафе можно прогуляться до Фишевой горы -- самой высокой точки Тихвина, пройтись по парку поколений -- современному интересному городскому пространству.

"Сибарит" (или "Сиропчик"), 3-й микрорайон, 5 -- кофейня с вкусным кофе и оригинальными десертами недалеко от центра. Официально открывается в 9 утра, но когда мы пришли за кофе примерно в 9:24 кофейня ещё была закрыта. Возможно, раньше место называлось "Сиропчик", но потом они решили не открываться слишком рано и переименовались в "Сибарит". Тем не менее здесь можно уютно посидеть и почитать литературу. Видел тут среди книг биографию Орджоникидзе.

"Крем", 3-й микрорайон, 2/3 -- ещё одна неплохая кофейня. В "Креме" можно найти неплохой кофе, стандартные десерты (такие же как в каждой второй кофейне) и неплохую выпечку. Также в кафе вам могут подать роскошные ягодные чаи.

"Тайм драйв", Карла Маркса, 30 -- по сути это детский развлекательный клуб и кафе в одном помещении. Поэтому могу дать два совета: если вы категорически против детей, обходите заведение стороной, но если вы приехали в Тихвин с ребёнком, это ваше основное кафе. Мы с женой из второй группы, приезжали в город с двухлетней дочкой и все втроём были в восторге от места. Пока ребёнок играет в безопасной среде с сетками и мягкими углами, родители могут спокойно поесть. В будний день стоимость игрового часа для ребёнка -- 250 рублей.

В первый день пребывания в городе мы заказали бургер, рыбную "шаверму", наггетсы, креветки в панировке, овощную тарелку, кофе и молочный коктейль. Такой щедрый стол обошёлся нам всего в 1360 рублей. При этом качество еды не вызывало никаких нареканий.

Чешский двор, Карла Маркса, 32 -- один из неплохих ресторанов города. Готовят хорошо и вкусно, могут предложить один вид разливного пива, что для города скорее исключение. Чешским колоритом заведение похвастаться не может, музыка в заведении рассчитана на старшее поколение, а не на молодёжь. Достойный ресторан средней руки.

Каравелла, Знаменская, 50 -- ресторан на малоизученном краю города. Мы заходили в него пять лет назад, всё, что я помню -- это хорошая кухня, большое количество свободных посадочных мест и довольно долгое обслуживание. Возможно, за пять лет что-то изменилось, но место стоит рассмотреть для посещения.

Монастырская Трапезная, Тихвинская, 1 -- все дороги города Тихвин ведут в Тихвинский монастырь на Тихвинской улице. Еда в монастырской трапезной очень вкусная. Рыба по-монастырски, калитки, ягодно-травяные чаи и вот это вот всё. Цены гуманные, но примерно рублей на 50 выше, чем, например в "Тайм Драйв".

Монастырский квас - это уже веский провод посетить город. Монахи готовят великолепный натуральный хлебный квас с изюмом, который примерно 1-2% алкогольный. Вкус сложно описать словами -- он одновременно сладкий, хлебный и кислый, но всего в меру. Лучше всего выбирать традиционный квас, по 150 рублей за литровую бутылку, а не ячменный или пшеничный, по 300 рублей за бутылку. Ячменный и пшеничный -- это по сути пиво с 5-7% алкоголя. Они пьются гораздо легче пива и могут оказаться коварный эффект, когда хочешь подняться, а ноги уже немного неуверенные.

=== Прочие места

Если будет время, можете праздно прогуляться по "Захаровскому парку" рядом с монастырём. Летом под сенью деревьев гулять прохладно, а ещё можно пообщаться с утками и белками, населяющими парк и прилегающий пруд. Летом возле пруда работает лодочная станция, открываются аттракционы, можно застать местных козлов и пообщаться с монастырскими котами.

Если вы приехали в разгар летней жары, съездите искупаться на Царицыно озеро. От центра города часто ходит автобус, расписание которого можно подсмотреть https://rasp.yandex.ru/bus/tsaritsyno-ozero-saint-petersburg-and-leningradskaya-oblast-s9811031--tixvin[на Яндексе]. Озеро чистое, приятное, в нём можно купаться и добираться до него совсем недолго.

Посетите Бокситогорск всего в получасе езды от Тихвина. Мы заехали в него на час, в самый центр, около здания администрации. Главная достопримечательность Бокситогорска -- большая надпись "Я ЛЮБЛЮ ЛЕНОБЛАСТЬ" рядом с Церковью Покрова Пресвятой Богородицы. Церковь тоже интересная, внутри много икон. К сожалениью, я не разбираюсь в важности икон, но заглянуть было интересно. Город уютный, но совсем не туристический.

Побывайте в Дымском Монастырев деревне "Красный броневик". Я ничего не знаю об этом монастыре, видел его только указатель по дороге. Из того, что я узнал о месте в интернете, мне кажется, что это интересное место. Вокруг Тихвина разбросано столько других монастырей, что можно провести неделю в городе и ни разу не повториться в выборе места для очередной туристической вылазки.

== Заключение

Тихвин определённо стоит посетить. Этот небольшой городок в ленобласти порадует вас низкими ценами, комфортом и размеренным ритмом жизни. Его можно пройти пешком от края до края всего за час. Возможно, поэтому местные никуда не торопятся в отличие от жителей больших городов. Даже светофоры здесь не торопятся. На Х-образном перекрёстке после красного света для машин сначала загорается зелёный для всех пешеходов по всем четырём направлениям и только потом -- зелёный для машин. Отличное место для отдыха всей семьёй.
