= Почему фильмы Джима Джармуша собирают полные кинотеатры?

Джим Джармуш -- независимый режиссёр из США. Он снимает фильмы не ради популярности, не ради денег, а потому что может. Ему это нравится и это видно в каждой ленте по одновременно загадочной и смешной атмосфере. Роуд-муви с Деппом в роли мертвеца, Бил Мюррей с цветами или против зомби и, конечно же, неповторимый юмор. Расскажу о каждом фильме, чего ожидать, с чего начать знакомство и на что обратить внимание.

Мне всегда казалось, что артхаус -- это что-то сложное, мутное и непонятное. Однажды я посмотрел фильм Джима Джармуша и понял, что артхаус может быть совсем разным: понятным и даже смешным.

Сначала мы с Женой посмотрели "Таинственный поезд", потом "Мертвеца", потом, "Сломанные цветы", 2005. Залпом мы посмотрели все произведения режиссёра. В этом году случайно решили пересмотреть их по порядку. По счастливому совпадению в этом году Джиму Джармушу исполнилось 70 лет. В его фильмах можно не беспокоится о спойлерах, потому что каждый понимает сюжет по-своему. Важно ощущение присутствия и то приоткрытое окно в жизнь героев, что видно с экрана.

Зачастую в его фильмах нет даже концовок, некоторые специально сделаны так, чтобы у главного героя не было имени, не было истории, но каждый из них офигенный. Делюсь впечатлениями и небольшим гайдом о том, почему обязательно нужно посмотреть специфическое кино не для всех. Если вам не понравится, я съем свои тапки.

== Permanent Vacation, 1980

"Отпуск без конца" - самый первый, но очень хорошо узнаваемый фильм Джармуша. Сюжет можно изложить одним предложением: парень из Нью-Йорка решает навестить свою мать в психушке, а потом уезжает в Париж в перманентный отпуск и очень скучает по родному городу. Чувство, знакомое многим русским мужикам после сентября 2022 года.

Отпуск без конца нельзя назвать выдающимся, но его надо посмотреть целиком, чтобы потом осознать отдельные сцены.

Две минуты посредственного танца в пустой комнате с девушкой, сидящей у окна. Сцена не содержит ни слова, но говорит многое о перспективе отношений парня Олли с его девушкой.

Диалог с поехавшим мужиком на развалинах дома: "Какая война, это вертолёты, у вьетнамцев даже нет вертушек". Как будто он всегда знал, как разговаривать с сумасшедшими. А вообще сюжет заставляет задуматься, может быть, сумасшедшие -- это мы.

Почему эта женщина сидит на ступеньках в таком виде? У неё всё хорошо? Зритель не получит ответа, но у него будет время об этом поразмыслить.

Не стоит начинать с этой полнометражки, фильм снят на бюджет в 12 тысяч долларов, но если понравились другие фильмы, посмотрите и этот.

== Stranger than paradise, 1984

"Более странно, чем в раю" получился значительно лучше первого фильма.

Бюджет в разы больше чем в первый раз -- 100 000 долларов! А спонсором выступила Сара Дайвер, нынешняя супруга Джармуша, она появляется в небольшом камео. Также она есть в титрах к каждому фильму Джармуша. Даже если её не было в ролях, она всё равно упоминается как вдохновение.

Сюжет рассказывает историю трёх героев: Вилли, его друг Эдди и двоюродная сестра Эва. Изложить сюжет одним предложением сложно, но он вполне умещается в двух: Вилли и Эдди живут в Нью-Йорке, зарабатывают на лошадиных бегах и карточных играх, когда к Вилли ненадолго приезжает из Венгрии его сестра Эва. Вскоре она уезжает в другой город, а друзья остаются и продолжают заниматься всё тем же. Через год, зимой, они решают поехать в гости к Эве, встречаются с ней, её парнем, который ей не очень-то и нравится, а вскоре они все втроём спонтанно срываются в тёплую Флориду.

Ладно, схитрил, использовал три предложения, но суть ясна.

По жанровой принадлежности фильм является комедией. Но не комедией типа фильмов с Джимом Керри. Как таковых юмористических моментов в комедии нет -- юмор понятен только в контексте. Вот, например, в первый день после прибытия во Флориду парни уходят на собачьи бега, Эва весь день остаётся сторожить номер в мотеле. Не то чтобы ситуация сама по себе была смешная. Смешно становится, когда она жалуется им на то, что в свой отпуск во Флориде она должна сидеть весь день в мотеле.

Лучшие моменты в мелочах. Например, платье -- подарок Эве от брата. Она совсем не оценила такой подарок, но носит, потому что подарок. "Мне не  кажется, это платье не очень красивое", говорит Эва. "Оно красивое, ведь я его не просто так выбрал", отвечает Вилли.

Когда позже в подворотне Эва стягивает с себя это платье, она говорит Эдди, что никогда не любила это дурацкое платье.

Ещё сцена, когда Эва включает свою любимую песню в машине по пути во Флориду. Вилли постоянно требовал выключить эту песню, когда слышал, а Эдди услышал впервые и ему понравилось. Вилли обвиняет их в том, что они спелись. Это правда смешно, когда смотришь фильм, в отрыве от сюжета это обычные ситуации.

Взаимоотношения и характеры героев раскрываются именно в таких сценах как с платьем, песней или кроватями. Когда они прибывают во Флориду. Приезжают в ночи, ложатся спать: "Эва, ты спишь на раскладушке". Эва очень сонно ложится на диван и бормочет "Ничего подобного, сами спите на раскладушке", после чего Эдди ещё несколько минут сражается с раскладыванием раскладушки.

На второй день во Флориде парни идут не на собачьи, а на лошадиные бега, а Эва внезапно становится очень богатой. И то, как она богатеет тоже смешно, потому что абсурдно -- её путают с кем-то другим, не успев среагировать, она получает пачку денег.

Концовку фильма тоже абсурдно смешная в контексте: в силу обстоятельств и полной несогласованности действий в конце Вилли летит в Будапешт, Эва остаётся в номере, Эдди сидит в машине у взлетной полосы и смотрит на улетающий самолёт. Притом изначально улетать собиралась Эва, но передумала.

Наверное, это главная особенность юмора Джармуша во всех его фильмах -- абсурдность ситуаций, которая предоставляется как есть, без пояснений и трактовок.

Эву играет актриса Эстер Балинт, Ричард Энсон играет Эдди, а Джон Лури играет Вилли. Помимо выдающейся фильмографии Джон Лури также известен как автор первого мема рунета -- "Превед Медвед". Он же написал саундтрек к фильму, хоть саундтрека в фильме довольно мало.

Если вас не отпугивает чёрно-белая картинка и не самая захватывающая история, можете попробовать начать знакомство с работами режиссёра с этой ленты.

== Down By Law, 1986

Третий полный метр Джармуша -- "Вне закона" вышел уж очень удачным.

Можно быть скептически настроенным к чёрно-белому артхаусу, но этот фильм правда очень хорошо сделан именно за счёт чёрно-белой гаммы, создающей нужную атмосферу.

Сюжет снова простой: двое мужчин ссорятся со своими подругами, потом каждому предлагают очень выгодное и незапарное дельце, которое оказывается подставой. Сюжетные линии развиваются параллельно, пока Зак (Том Уэйтс) и Джек (Джон Лури) не встречаются в тюрьме.

Сначала они сидят в камере вдвоём, но позже к ним подселяют итальянца по имени Роберто (Роберто Бениньи). Вскоре они сбегают, а в конце расходятся в три разные стороны.

По контрасту с первыми двумя лентами, это фильм немного непривычно наполнен диалогами и даже движением. Приём, который станет более оформлен в следующих картинах. Статичных сцен почти нет, герои очень живые.

Саундтрек снова сочинил Джон Лури. Но Тома Уэйтс, играющий одну из главных ролей тоже не остался в стороне. Результатом стало почти полное отсутствие немых сцены или моментов многозначного молчания, а те, что есть совсем не напрягают.

Самая лучшая часть этого фильма -- игра Бениньи и сочные диалоги и монологи:

- За что тебя посадили, Зак?
- Меня подставили, я невиновен.
- А за что тебя, Джек?
- Меня подставили, я невиновен.
- Роберто, скажи, а за что тебя посадили?
- Я убить человека.

Монолог Роберто у костра -- отдельный вид искусства: "Моя мама любила кроликов, она их сначала гладила, а потом бам! И нет кролика. Иногда мне снится, что я кролик и мама меня хочет убить. Но я люблю свою маму, она хорошая".

Роберто Бениньи преображает ленту. Недаром эта роль принесла ему мировое признание. Раньше его знали только на родине, но после "Вне закона" его признали как актёра мирового уровня. Он смог превратить неспешную тюремную историю в смешную комедию о побеге и любви. При этом ему даже не особенно пришлось играть, так как женщина, с которой он остался в конце -- его жена.

Восхитительный фильм, заслуживающий просмотра. Им можно смело начинать знакомство с творчеством Джима Джармуша. Не обращайте внимания на чёрно-белый кадр, цвет здесь совсем не важен.

== Coffee and Cigarettes, 1986

В том же году выходит первая глава "Кофе и сигареты". С этого момента Джармуш перестаёт пить кофе. Сигареты не бросает.

Но произведение будет закончено и выпущено только в 2003 году, не буду забегать вперёд.

== Mystery Train, 1989

В 1989 Джармуш выпускает четвёртый полнометражный фильм и он даже не чёрно-белый.

Сюжет "Таинственного поезда" поделён на три главы: "Вдали от Йокогамы", "Призрак", "Потерянные в космосе". Каждая глава рассказывает историю одного вечера с точки зрения разных людей.

"Вдали от Йокогамы" показывает двух молодых японцев, приехавших на родину Элвиса, в Мемфис. Они посещают места славы рок-н-ролла и постоянно о чём-то спорят. Такие молодые, наивные и забавные ребята: Джун (Масатоси Нагасэ) и Мицуко (Юки Кудо).

После осмотра достопримечательностей ребята заселяются в местный отель-клоповник.
На ресепшене сидят два чернокожих клерка: молодой паренёк и мужчина постарше. Диалоги с участием клерков на ресепшене -- одни из самых смешных моментов в фильме.

Диалог двух клерков, когда Мицуко вместо чаевых даёт молодому парню японскую сливу:

- Ты будешь её есть? - спрашивает старший клерк
- Я не уверен. - отвечает парень
- Не советую тебе её есть.
- Да, пожалуй, не буду.
- *Старший клерк съедает сливу - единственный аналог чаевых, доставшийся парню.*

Утром японцы пакуют вещи и слышат выстрел. Начинается вторая глава.

В главе "Призрак" Луиза (Николетта Браски), недавно овдовевшая итальянка, собирается перевезти гроб с телом мужа в Рим, но рейс задерживают. Она скитается по вечернему Мэмфису, а когда к ней прилипают местные гопники, заселяется в тот же отель.

На входе она сталкивается с девушкой по имени Ди Ди (Элизабет Бракко), после небольшого диалога, они решают взять один номер на двоих. Ди Ди постоянно о чём-то треплется, не замолкает ни на секунду, поэтому когда она наконец засыпает, даже зрителю сразу становится спокойно.

Ночью Луизе является призрак Элвиса. Утром женщины съезжают из номера и слышат выстрел. В этот момент я как зритель такой: "Ух-ты! Сюжеты-то связаны, а я-то думал, они независимы!"

Третья глава "Потерянные в космосе" дорисовывает перед смотрящим картину вечера в Мэмфисе. Джонни -- бывший парень Ди Ди, Чарли -- брат Ди Ди и Уилл -- общий друг, трое парней устраивают стрельбу в магазине спиртного и ищут укрытие на ночь в том же отеле. В утреннем разговоре Джонни узнаёт некоторую горькую правду о Чарли и с горя пытается застрелиться. Чарли и Уилл пытаются отнять пистолет, но в потасовке пистолет стреляет, пуля попадает в ногу Чарли.

На этом моменте при первом просмотре мои мысли выглядели примерно так: "Это смешной и очень качественно завязанный сюжет, мне определённо нравится!". При повторном просмотре фильм всё ещё выдерживает планку. Но зная основную канву сюжета, можно подметить мелкие интересные детали.

А теперь несколько слов о подборе актёров и общей атмосфере фильма. Актёрский состав каждого фильма Джармуша почти семейный. Например, Николетта Браски, играющая Луизу -- жена Роберто Бениньи. Роль старшего клерка исполнил Screaming Jay Hawkins, которым заслушивалась Эва из "Более странно, чем в раю". Саундтрек к "Таинственному поезду" написал Джон Лури. А на роль голоса радио-диджея был приглашён Том Уэйтс. Джонни сыграл легендарный Джо Страммер, который нигде больше не фигурировал, но служил вдохновением. Чарли играет Стив Бушеми, он ещё сыграет в другой ленте режиссёра. Масатоси Нагасэ (Джун) тоже ещё появится в другом фильме.

"Таинственным Поездом" можно смело начинать знакомство с режиссерскими работами Джармуша. Собственно, у меня так и получилось, "Таинственный поезд" открыл для меня новый мир в кинематографе.

== Night on Earth, 1991

В картине "Ночь на Земле" 1991 года Джармуш снова применил разделение на главы.

Пять зарисовок про таксистов и их пассажиров в одну ночь. События разворачиваются в пяти городах мира: Лос-Анджелес, Нью-Йорк, Париж, Рим, Хельсинки.

Первая часть -- в Лос-Анджелесе, за рулём такси сидит молодая девушка Корки (Вайнона Райдер). Она уже спланировала всю свою жизнь наперёд. Она хочет водить такси, выйти замуж и родить детей. Корки подкупает искренностью и контрастом по сравнению со своей пассажиркой из высшего света.

Вторая часть происходит в Нью-Йорке таксист -- Хелмут, но этот клоун не умеет водить и не знает город, поэтому всю дорогу за рулём едет пассажир по имени ЙоЙо. Хелмут действительно клоун, мигрировавший из ГДР. Наверное, самая смешная зарисовка. Много шуток про имена "Хелмут (Шлем)" и "ЙоЙо (игрушка)". Но юмор очень дружелюбный и общая атмосфера второй части очень душевная.

В Париже роль водитель из Кот-д'Ивуар (Исаак де Банколе) везёт незрячую женщину и задаёт ей бесконечные вопросы об отсутствии у неё зрения. Она мастерски парирует любые аргументы и к концу сюжета торжествующе улыбается, когда водитель попадает в ДТП со словами "Ты слепой что ли". Смешно, как слепая женщина оказывается видящей лучше, чем зрячий таксист.

Таксист из Рима по имени Гино (Роберто Бениньи) подвозит священника. Гино исповедуется в своих грехах, пока Священник постепенно умирает по дороге. Грехов у Гино хватает: сексуальные отношения с овощами, животными и женой брата. Это как минимум. Истории грехов не звучат плоско, потому что Гино правда раскаивается в содеянном и хочет исповедаться. Но КАК он их рассказывает! Это нужно видеть.

Финский таксист Мика из Хельсинки подвозит трёх пьяных мужиков. Один пьян настолько, что пребывает в отключке почти до конца сюжета. Это самая драматичная зарисовка. Сначала кажется, что у пьяного в отключке пассажира жизнь тяжёлая: уволили с работы, разбили новую машину, но когда таксист рассказывает свою историю, это заставляет двух неспящих пассажиров пролить слёзы.

Несмотря на то, что сценарий был написан всего за восемь дней, это одна из лучших лент в фильмографии режиссёра. На экране мы видим в первую очередь людей, живущих своей жизнью, таксистов, а не героев фильма. Водители и пассажиры настраиваются на одну волну, формируют связь, поставленную в центр сюжета. Именно эта связь делает произведение запоминающимся благодаря открытости и честности каждого из персонажей.

Сам режиссер определенно запомнил этот опыт. Во время съёмок в Италии прибыла полиция, но полицию не убедил ответ на вопрос "кто такие и что здесь делаете". Поскольку паспорта съёмочная группа забыла в отеле, всем пришлось провести увлекательное время в отделении.

Другой незабываемый опыт -- сёъмки в салоне машины на ходу. Это само по себе сложная затея, но вдвойне сложно, когда стоит задача ещё и передать ночную атмосферу города. Оператор (Фред Элмс) хорошо запомнил опыт взятия кадра на 14-градусном морозе в Финляндии.

Хельсинки подарил эмоции и актёрам, когда съёмочная Вольво 144 остановилась на путях перед приближающимся трамваем. Избежать столкновения удалось чудом.

Актёрский состав ленты впечатляет. Ниже не какой-то случайный список имён, а реальный состав актёров в порядке появления:

Лос-Анджелес:

- Вайнона Райдер
- Джина Роулендс

Нью-Йорк:

- Джанкарло Эспозито
- Армин Мюллер-Шталь
- Рози Перез

Париж:

- Исаак Де Банколе
- Беатрис Даль

Рим:

- Роберто Бениньи
- Паоло Боначелли

Хельсинки:

- Матти Пеллонпяя
- Кари Вяянянен
- Сакари Куосманен

Саундтрек к фильму сочинил Том Уэйтс.

С "Ночи на Земле" также можно не раздумывая начинать знакомство с фильмами Джармуша. Этот фильм имеет все шансы занять место в вашем пантеоне любимых лент.

== Dead Man, 1995

"Никогда не путешествуйте с мертвецом", гласит слоган фильма "Мертвец" 1995 года.

Это мы смотрим, это мы любим и ценим! Наверное, самый простой способ начать смотреть Джармуша. Фильм с ещё юным и свежим Джонни Деппом. И можно смело сказать, что он умер. Ну, по крайней мере физически. Ну, то есть в конце ленты. А может и в начале. Это зависит, с какой стороны посмотреть. Нет, погодите, он же умер, да? А, ладно. Сами можете решить при просмотре.

Действие происходит на диком западе. Так что технически это вестерн, очень своеобразный вестерн. Сюжет прост: парень по имени Уильям Блейк приезжает в глухой захолустный город "Машин" на работу. Но он опоздал, место уже занято. Он проявляет сочувствие к одной девушке. Они спокойно лежат одетые в постели и разговаривают, когда приходит бывший парень этой девушки по имени Чарльз Диккенс. Она говорит, что никогда его не любила, он обижается и стреляет в неё из револьвера. Пуля проходит насквозь, убивает девушку и намертво заседает в сердце Уильяма. В ответ Уильям Блейк достаёт пистолет и с третьего выстрела убивает Чарльза Диккенса. Уильям Блейк убил Чарльза Диккенса -- это одновременно смешно и несёт в себе глубокий смысл.

Я описал только первые 30 минут ленты продолжительностью в два часа. Что происходит в оставшиеся полтора часа? Это лучшая часть фильма, в которой Уильям Блейк умирает. Да, он умирает в течение полутора часов экранного времени.

Постепенно Уильям превращается из жалкого ботаника в опасного серийного убийцу. На пути он встречает индейца по имени "Никто" -- большого фаната поэзии настоящего Блэйка. Основной мотив "Мертвеца" -- это взаимодействие, развитие и преображение персонажей. Это путь с этого света на тот, рассказанный через путешествие по Америке.

Можно написать не одну научную работу на тему аллюзий, отсылок и символических иносказаний в фильме. Мертвеца можно разворачивать слой за слоем: вестерн, роуд-муви, отсылки к Блейку, тема Америки, тема путешествия к свету, тема смерти, использованные образы. Но можно и просто посмотреть фильм, не углубляясь в подтекст, просто получить удовольствие.

О Мертвеце написано и сказано больше, чем о любой другой картине Джармуша. Хватает и положительных и отрицательных отзывов. Например, после первого показа на Канском фестивале не было привычных аплодисментов, лишь один человек встал и сказал "Джим! Это дерьмо!".

Премьера в кинотеатрах состоялась только спустя год после первого показа. Но даже это не спасло ленту от провала в прокате, потому что в штанах только 37 кинотеатров согласись крутить у себя "Мертвеца". При бюджете в 9 миллионов долларов картина собрала всего 1. Даже уже вполне известный Джонни Депп в главной роли не спас ситуацию. Игги Поп, показавшийся в кадре в женском платье, тоже не помог.

А вот аудитория и некоторые (в основном не Американские) критики приняли картину хорошо.

Истина всегда посередине. Фильм очень нетипичный для американского производства, а тем более для вестерна. Это скорее роуд-муви о путешествии человека: духовном и физическом. Фильм об Америке, который не понравился американцам. Но этой необычностью и странностью он подкупает.

До просмотра я был настроен слегка скептически по отношению к фильму, но к концу ленты расставаться уже не хотелось, я успел привыкнуть к этой неспешной и немного мистической атмосфере преображения.

Не последнюю роль в создании атмосферы играет саундтрек, сочинённый Нилом Янгом. В любой картине Джармуша саундтрек составляет чуть ли не треть смысловой нагрузки. Его важно слушать и дать ему приникнуть в сознание.

В общем, это типичная лента-эксперимент от режиссёра, который делает не то, что будет востребовано, а реализует свою необычную идею, уникальное видение привычного мира. Фильм чурно-белый, но его определённо стоит смотреть, им совершенно точно можно начинать знакомство с работами Джармуша.

== Ghost Dog, 1999

Следующая по очереди лента -- "Пёс-призрак: Путь самурая", 1999 года.

Это, кхэм, гангстерский боевик с чернокожим самураем в главной роли, только самурай на самом деле человеческое воплощение чёрного медведя гризли.

На полном серьёзе. Главный герой -- чернокожий парень по имени Пёс-призрак. Но он больше похож не на пса, а на медведя, ою этом неоднократно немекают в сюжете: книгой про медведей на французском, сценой с браконьерами, убившими гризли, пижамой с медведями на девочке по имени Перлин.

Пёс-призрак считает себя самураем, вассалом гангстера по имени Луи ещё с юных лет, когда Луи спас ему жизнь.

Луи -- один из членов криминального клана, он использует Пса-призрака, чтобы избавить дочь главы клана от неугодного любовника. Луи заказывает Псу-призраку убийство. Но убить члена собственного клана -- большое преступление, у которого не должно быть свидетелей на стороне, поэтому главы клана решают убрать Пса-призрака.

Избавиться от главного героя фильма не так просто. Весь фильм посвящён противостоянию клана и темнокожего самурая. Каждый новый сюжетный поворот предваряется выдержками из кодекса самурая, иллюстрирующими те или иные сцены. Этот приём дополняет атмосферу строгих порядков японского средневековья.

Так и хочется сравнить ленту с "Мертвецом", но это будет плохое сравнение. Во-первых, бюджет картины всего два миллиона, а сборы аж 9.3 миллиона. "Мертвец" провалился в прокате по независящим от него обстоятельствам, но всё же его бюджет несравнимо больше и он действительно более красивый, даром что чёрно-белый. "Путь самурая" цветной, но выглядит слабее и не обладает таким же глубоким подтекстом.

"Пёс-призрак" не может порадовать сочной картинкой и скорее всего вас разочарует после "Мертвеца". Тем не менее лента достойна внимания и может рассматриваться как типичное произведение Джима Джармуша.

Саундтрек к фильму сочинил RZA (Wu-Tang Clan). Музыкальный коллектив и режиссёр очень близки, такая дружба отразилась в совместной работе над музыкой к фильму.

== 10 minutes older, 2002

На 10 минут старше: Труба.

10 минут Джармуша и ещё 80 минут других режиссёров. 93 минуты артхаусного междусобойчика.

Это компиляция из нескольких коротких сюжетов в индивидуальном стиле разных режиссёров. В ленте приняли участие наиболее известные творцы артхауса. На удивление неплохоц сборник.

Джим сделал сюжет про актрису, которая на своём 10-минутном перерыве говорит с любимым человеком по телефону, пока все вокруг её отвлекают всеми возможными способами.

Большая часть сюжетов тоже достойна внимания. Мне особенно понравился сюжет про сумасшедшего китайца. Очень сильный получился также сюжет про индейцев и тот про умирающего парня в машине.

== Coffee And Cigarettes

Кофе и сигареты, 2003.

Теперь можно и про самый главный труд Джармуша поговорить. Это 11 зарисовок, которые режиссёр снимал семнадцать лет. Как я уже говорил, после того, как Джармуш отснял первый сюжет про кофе и сигареты с Роберто Бениньи в 1986, он перестал пить кофе. Но сигареты не бросил. Тогда режиссеру было 33. Сейчас ему 70. Получается, он не пьёт кофе уже 37 лет. Любопытно.

Каждая сцена ленты показывает одного или несколько самых любимых актёров, музыкантов или шоуменов от Джима. Все 11 эпизодов объединяет общая тема: кофе и сигареты. Люди в кадре либо пьют кофе, либо курят сигареты, либо делают и то и другое сразу. Диалоги всегда очень остроумные, хоть могут местами быть странными.

Как правило, актёры либо играют сами себя, либо не называются по имени. В съёмках приняли участие почти все любимые люди режиссёра: Том Уэйтс, Игги Поп, Билл Мюррей (работающий официантом), Wu-Tang Clan, Роберто Бениньи, Стив Бушеми, The White Stripes и многие другие. Заскучать перед экраном не получится при всём желании.

== Broken Flowers, 2005

Сломанные цветы, 2005 года - удивительно смешная комедия о поиске сына.

Джармуш балует нас цветной картинкой и матёрым актёром - в главной роли Билл, мать его, Мюррей!  Мужчина по имени Дон Джонстон работает кем-то вроде системного администратора, построил свою карьеру на компьютерах, хоть сам его не имеет.

Если вы смотрели все фильмы Джима до этого момента, то сможете без труда узнать фирменный стиль: во-первых, имя главного героя, которое напоминает имя известного актёра - Дона Джонсона. Во-вторых, любимый человеческий контраст - Дон построил карьеру на компьютерах, но своего не имеет. До полного образа нужно дать герою ещё какую-нибудь нестандартную черту. Оказывается, что Дон, этот старый и не самый привлекательный мужчина - "кто-то вроде Дон Жуана", как не раз повторят по сюжету.

В лучших традициях излюбленноых джармушевских роуд-муви Дон получает письмо от анонимной любовницы, в котором сообщается, что у него есть сын. Лучший друг Дона, помешанный на детективах, отправляет Дона в путешествие навещать своих любовниц, чтобы узнать, какая из них родила ему сына.

Любовницы тоже не так посты:

- У одной из них (Шэрон Стоун) похотливая дочь и бизнес - она организует шкафы.
- У другой, бывшей хиппи (Фрэнсис Конрой), бизнес в недвижимости вместе с мужем.
- Третья (Джессика Лэнг) - коммуникатор с животными. Нет, она не читает мысли животных, а только слышит их, если те с ней говорят.
- Четвёртая (Тильда Суинтон, выглядящая как женщина) живёт на ранчо в глуши вместе с группой агрессивных байкеров.

Дон ищет улики, которые выдали бы автора записки: розовый цвет, дети, печатная машинка, но чем дальше продвигается сюжет, тем больше он видит улики там, где их нет.

Но самая замечательная сцена - это концовка, в которой мелькает реальный сын Билла Мюррея - Гомер Мюррей. Только ради этого момента стоит посмотреть Сломанные цветы.

Лента отличается приятным и грамотно подобранным саундтреком. Основную часть сочинил эфиопский композитор Мулату Астатке.

Любопытно, что "тема Дона Джонстона", игравшая во время его путешествий - на самом деле известная джазовая композиция "Song For My Father" в обработке Мулату Астатке.

Кроме Мулату над музыкой для картины работали ещё как минимум восемь коллективов: от гаражного рока до классический музыки.

Прекрасная лента во всех проявлениях.

== The Limits of Control, 2009

Пределы контроля, 2009.

Фильм вобрал в себя опыт других работ режиссёра. Например, можно найти общие мотивы с "Таинственным поездом", когда сюжет постепенно подходит к развязке, но почти до конца неизвестно, в чём же эта развязка заключается.  Можно найти что-то общее и с "Мертвецом" - такая же странная неспешная атмосфера, только без глубоких тем, которыми был пропитан "Мертвец".

Кроме того, что "Мертвец", что "Пределы контроля" получили плохие отзывы критиков. Но есть отличия: фильм с Деппом занизили в рейтингах, потому что тот не оправдал ожиданий критиков, а вот картина 2009 года, вероятно, заслужила низкие оценки.

После просмотра у зрителя может возникнуть вопрос "а какого, собственно, хрена я посмотрел". Если зритель сможет досмотреть, как на протяжении 1 часа 56 минут мужчина в костюме (Исаак де Банколе) пьёт "два капучино в двух отдельных чашках".

Сюжет по славной традиции повествует о передвижении главного героя из точки А в точку Б. Но этот главный герой не так прост: на своём пути он встречает людей, которые начинают разговор с кодовой фразы "Вы не говорите по-испански?", после чего продолжают словами в духе "Вы интересуетесь искусством/молекулами/фильмами?". Как правило, это односторонний диалог, потому что главный герой почти никогда не говорит что-то длиннее односложных реплик. Разговоры эти, как правило, сами являются отсылками к тем или иным произведениям культуры.

Из примечательных людей на пути можно выделить Тильду Суинтон и полностью обнажённую женщину (Пас де ла Уэрта).

Периодически в сюжете повторяются фразы "Всё субъективно", "Вселенная не имеет ни центра, ни краёв; реальность условна" и "Тот, кто думает, что он важнее других, должен отправиться на кладбище. Там он увидит, что жизнь — ничего более, чем пригоршня праха".

Это медленный фильм, который раскрывается в самом конце. Хоть к концовке у меня и есть несколько вопросов, я не буду их озвучивать, чтобы не спойлерить сюжет.

По признанию режиссёра картина целенаправленно сделана такой. У персонажей нет имён, нет прошлого, нет будущего, возможно, они даже не настоящие люди, а метафоры. Это своеобразный эксперимент от противного: сделать всё не так, как принято у американцев.

Саундтрек для Пределов контроля не был специально записан, а был выбран из уже существующих треков, подходящих к нужным сценам по атмосфере и смыслу. Если такого трека не находилось, Джим сам его записывал со своей группой Bad Rabbit.

Если вы посмотрели несколько работ Джармуша и вам понравилось, посмотрите и эту ленту. Иначе смотреть не советую.

== Only lovers, 2013

Выживут только любовники, 2013.

Наглядный пример того, что будет, если Джим Джармуш сделает мистическую хоррор-драму про вампиров. А именно, ему опять не дадут денег в штатах, фильм будет спродюсирован на средства Великобритании и Германии.

Сюжет рассказывает историю пары вампиров, которые состоят в браке, но живут в разных сторонах света.

На главную роль была призвана Тильда Суинтон. В "Пределах контроля" она была хороша, но непростительно мало. В "любовниках" её мастерство появилось во всей красе, включая обнаженную. Тильда играет роль женщины-вампира по имени Ева (Eve).

Вторая главная роль - Том Хиддлстон в образе апатичного музыканта-вампира по имени Адам.

Первая половина фильма примерно такая: Ева, живущая в Танжере, прилетает в гости к Адаму, живущему в Детройте, они милуются и проводят время вместе. Это наиболее неспешная часть, но всё меняется, когда к ним внезапно решает наведаться Эва (Ava), младшая сестра Евы, из Лос-Анджелеса. Эву играет Миа Васиковска.

Эва рушит привычный размеренный уклад жизни пары. Уничтожает все самые дорогие вещи (и не только вещи), оставляет Адама и Еву в очень трудном положении.

Как я сказал в начале, финансирование для съёмок пришлось искать в Европе. Всего на съёмки было потрачено 7 миллионов долларов, а прокат в кинотеатрах принёс лишь на 600 тысяч больше. Как сказал сам Джармуш "становится всё сложнее и сложнее найти финансирование для немного необычных или непредсказуемых, или фильмов, которые не оправдывают какие-то ожидания людей".

И, честно говоря, эта картина действительно не совсем оправдала мои ожидания. При первом просмотре я дал"любовникам" 6 из 10. Конечно, я немного рубил с плеча, но это один наименее типичных фильмов режиссёра. Да, действие в основном происходит ночью, как во многих других его работах, но здесь нет той основной составляющей движения, это не роуд-муви. Пока в кадре не появляется Васиковска, действие почти стоит на месте.

Нет ничего плохого в статичной картине, особенно если смотришь Джармуша, это повод всмотреться в детали повнимательнее, вслушаться в диалоги, отсылки и т.д. Критики не поняли "Пределы контроля", от любовников они были в значительно большем восторге. Я не до конца понял "любовников", но очень сильно оценил саундтрек.

Музыка в основном записана группой Джима Джармуша под названием SQÜRL, лента открывается интерпретацией Funnel of Love. Другие отметившиеся исполнители: Zola Jesus, ливанская певица Ясмин Хамдан, но основные музыкальные темы на лютне сочинил Джозеф ван Виссем. Он лучше всего пояснил за музыку сам: "Лютня идёт против всех технологий, против всех компьютеров и против всего ненужного дерьма". Примерно теми же формулировками можно описать творчество режиссёра.

Посмотреть "любовников" точно стоит, чтобы сделать выводы, нравится ли вам такое или нет.

== Paterson, 2016

Патерсон, 2016

Парень по фамилии Патерсон (Адам Драйвер, которому пришлось получить права на вождение автобуса) водит автобус в городе Патерсон. Он любит сочинять стихи без рифмы. У него есть девушка Лора (Гольшифте Фарахани) и собака по имени Марвин. За 118 минут перед нами предстаёт неделя из жизни Патерсона. Каждый день он водит автобус (ура, роуд-муви!) по знакомому маршруту, а в перерывах пишет стихи. Лора каждый день занимается, чем придётся: то раскрашивает дом в чёрный цвет с белым кругами, то заказывает гитару, чтобы играть кантри.

Сюжет начинается с того, как Патерсон сочиняет поэму о любви к Лоре, сравнивая её с их любимым спичками с синей головкой. На коробке спичек синий шрифт. А стихи Патерсона выводятся на экране белым рукописным шрифтом. Обратите внимание, что конечные титры вводятся на экран рукописным шрифтом (режиссёр) и синим печатным шифром (Джим Джармуш). Режиссёр общается со зрителем даже после окончания сюжета.

Сюжет можно описать в нескольких предложениях, но я не буду. Почти до самого конца не покидает ощущение, будто вот-вот что-то пойдёт не так, потому что герои слишком гладко и благостно живут. Что-то действительно идёт не так уже под конец фильма, но не так страшно, потому что это Джармуш. Нет ничего, что нельзя пережить.

Каждый раз при просмотре начало мне кажется каким-то глупым, как будто ситуация наиграна, но каждый раз мне жалко, что сюжет кончился, я бы смотрел ещё. За почти два часа привыкаю к этой понятной жизни и персонажам, начинаю вспоминать свои "вечные" моменты, напоминавшие поэзию Патерсона.

На самом деле стихи, конечно, написал настоящий поэт - Рон Паджетт. В ленте использованы четыре существующие поэмы Паджетта и три сочинённые специально для фильма. Поэму "Water Falls", по сюжету написанную девочкой, написал сам Джармуш.

Музыка вновь написана группой SQÜRL.

Этот фильм подсадит вас на работы Джармуша. Обязательно посмотрите.

== Dead, 2019

Мёртвые не умирают, 2019

Как выглядит зомби апокалипсис по-джармушевски? Зомби тяготеют к тому, что было важно для них в жизни и протяжным кривым голосом произносят: "кофее", "шардонеее", "пароль от вайфая" или "игрушки" (дети-зомби тоже есть).

Подбор актёров максимально звёздный: Билл Мюррей (шеф полиции Клифф Робертсон), Адам Драйвер (офицер Ронни Петерсон), Тильда Суинтон, Стив Бушеми, Дэнни Гловер, Сара Дайвер, Том Уэйтс, Игги Поп, RZA, даже Селена Гомес и Стёржилл Симпсон - автор саундтрека.

Не стоит воспринимать ленту слишком серьёзно. Это самая абсурдная и самая простая  из всех работ режиссёра.

Во-первых саундтрек состоит из единственной песни - Стёрджила Симпсона - The Dead Don't Die. Она дала название фильму, она же играет по радио, в магнитофоне и на компакт-диске.

Во-вторых,  актёры не раз сломают третью стену, например так:

- Что это играет?
- Sturgill Simpson - The Dead Don't Die.
- Что-то знакомое.
- Так это саундтрек к фильму.

В-третьих, Тильда Суинтон улетает "к своим" на летающей тарелке.

В-четвёртых, персонаж Драйвера ездит в маленьком электрическом Smart и носит на ключах к нему брелок "Звёздные войны" (нельзя просто так взять и не пошутить).

И это уже не говоря про Игги-зомби, Тома Уэйтса, играющего отшельника и само название города, в котором разворачивается сюжет - Центервиль.

Картина держит серьёзно-абсурдный тон до самого конца и не отпускает зрителя. Шансы того, что "Мёртвые не умирают" вам понравятся примерно 50/50. Начинать знакомство с Джармушем лучше всё-таки с чего-то другого.

== Музыкальные фильмы

Джим Джармуш срежиссировал также несколько фильмов для любимых музыкантов: Taking Heads, Тома Уэйтса, Нила Янга, Игги Попа.

Эти работы стоит смотреть только если вы посмотрели все остальные и пребываете под большим впечатлением. Характерный режиссерский почерк узнаётся в них с большим трудом, да и нужно по-настоящему любить музыканта, чтобы смотреть фильмы про него.

== French Water, 2019

Нужно рассказать
