= Кражи, яхты, спорткары, часовые механизмы и бесконечные суды: тяжёлая история появления Snowrunner на свет

Более чем 10 миллионов человек объединяет любовь к сгегобегу-глиномесу. Некоторые даже играл в Spintires и Mudrunner и считают, что это должна была быть одна игра. Заварите чайку, включите ненавязчивое кантри, мы отправляемся в долгий рейс по дороге истории. В этой детективной истории расскажу, как небольшое хобби одного человека переросло в серию игр, почему три игры -- на самом деле одна и куда пропала Spintires.

== Выезд. Старый гараж.

Начало серии было положено первой демо-версией Spintires, которая вышла в 2009 году. Это был проект одного парня по имени Павел Загребельный. На тот момент Павел официально работал в Saber Interactive (Saber 3D). Помимо основной работы у Павла были увлечения: DirectX9, пляжные виды спорта и красивые женщины. Но одно увлечение тянулось с самого детства -- игры с грузовичками. Вспоминая детское увлечение, Павел в свободное время вот уже несколько лет делал демку Spintires.

Павел представил первую версию Spintires на конкурсе Intel Level Up и сразу выиграл приз за лучшие показатели производительности на многоядерных процессорах и приз за лучшую оптимизацию под графику Intel.

Автопарк в первой демке состоял всего из двух грузовиков: Краз 255 и КамАЗ 6460. Оба грузовика были точными копиями своих реальных прототипов и даже имели настоящие логотипы на решётке радиатора. Игру хвалили за уникальную физику деформации грязи.

Такой неожиданный успех привлёк внимание Oovee -- маленькой независимой компании без имени из Соединённого королевства. Oovee появилась только за год до конкурса и всё это время выпускала дополнения для серии Train Simulator. Представители компании остались под впечатлением от первой "демо-спинки" и предложили опубликовать его на своём сайте. Павел принял предложение.

Опубликованная на сайте версия была востребована, и в 2011 году Пашу попросили принять участие в разработке полноценного релиза. Парень стал работать на Oovee в качестве консультанта, одновременно будучи устроенным в Saber. Тогда же вышла очередная версия игры. На этот раз элементы итогового оверлея были немного переработаны, а грузовиков стало уже пять: КРАЗ 255 6x6, КамАЗ 5460 4x2 тягач, КамАЗ 6460 6x4 тягач, КамАЗ 6522 тягач в трёх вариантах и КамАЗ 65228 8x8 тягач. Это была всё ещё технодемка, но включала сразу 7 карт.

Взаимовыгодное сотрудничество продолжалось несколько лет, пока в 2013 студия не решила вывести игру на кикстартер, собрав без малого 61 тысячу евро (в разных источниках встречал разные суммы, короче, игра собрала больше запланированного). В этой версии была только одна машина -- МАЗ 535. Дифференциал и полный привод подключались отдельно по команде. В игре появился цикл дня и ночи и более красивая графика. Чуть позже был добавлен маленький скаут -- УАЗ 469 и возвращён КРАЗ 255. Примерно тогда же Загребельный решил уйти из Сабер, чтобы сосредоточиться всеми силами на своём проекте. На следующий год Spintires официально вышла в Стим. Это был феноменальный успех.

Спинка на время стала самой продаваемой игрой на платформе -- 100 000 копий было продано только за первые 18 дней. В автопарк состоял из 6 грузовиков: КамАЗ 6522 6x6 (вместо КамАЗа 6x4), УАЗ 469 (редизайн), МАЗ 537 (вместо 535), ЗИЛ 130 (новый), Урал 432010 (новый), МАЗ 7310 (новый огромный 8x8). Для грузовиков добавлены разнообразные модули и возможности "тюнинга", например возможность поставить обтекатель. Это уже частично было в предыдущих версиях, но в релизе выбор стал гораздо богаче. Появились разные колёса с разными характеристиками и несколько полноценных карт, а также лебёдка и шанс перевернуть грузовик (до этого они не переворачивались).

Но чем выше ты взбираешься, тем больнее падать. Неожиданный успех Spintires с 2014 по 2016 привлёк внимание, которое до сих пор давит весом пачки металлических балок на будущее серии.

== В лужу грязи на повышенной

До релиза Spintires Oovee стоила примерно 14 000 долларов. Через год с момента релиза игры компания стала стоить почти 1,4 миллиона долларов, а следующий год был ещё лучше. Основатель компании на радостях купил себе Мерседес за 165 тысяч баксов (который ему через две недели облили растворителем) и открыл несколько бизнес-предприятий.

Примерно в это же время, 2014-2016, золотой разработчик начал жаловаться в своих соцсетях на то, что работодатель платит вообще-то не всю оговоренную долю с продаж.

Павел писал у себя на странице ВКонтакте о том, что он закончил редактор модов и новый бесплатный DLC для игры, но англичанин из Oovee пропал вместе с деньгами, закрыв доступ в Стим. Павел выпустил редактор карт для текущей версии и назвал это концом Spintires.

Но сколько вообще студия должна была отдавать разработчику? Ровно половину доходов с продаж! Минус налоги и прочие расходы. Точных свидетельств о том, сколько получал Павел нет, как нет и точного дохода от продаж "Спинки", но деньги едва ли можно назвать маленькими. Сама студия отрицала все обвинения, говоря, что платили разработчику в полном объёме.

Игроки не знали, что происходит за занавесом, вместо этого молча следили за закатом игры: через год после запуска обновления постепенно замедлились, а потом и прекратились вовсе. Игра осталась с множеством неисправленных багов и разными желаемыми, но нереализованными функциями.

Но за время активной разработки игра всё же успела получить несколько маленьких исправлений и полноценных DLC. Первое большое обновление принесло в игру новую карту "Наводнение" и несколько грузовиков: КамАЗ 6520 (он вернулся), ЗИЛ 131, Кировец К700 (ещё отзовётся эхом в Snowrunner), Урал 4320, МАЗ 535 (вместо 537, который только на релизе появился; серьёзно, зачем было их так тасовать?).

Другое большое обновление в районе 2015 добавило в игру 1 новый грузовик: ГАЗ 66 и удалило два старых: Урал 432010 и совсем недавно появившийся ЗИЛ 131. Все остальные грузовики получили обновленные модельки: лучшая детализация, анимация водителя, анимированные механизмы карданных валов и т.д. Это было то самое обновление, которое должно было символизировать конец Spintires по словам Павла, именно с этим обновлением в игре появилась поддержка модов. Кроме того появилась система, позволявшая выбирать грузовики перед началом карты в зависимости от доступных очков баланса. Общее число доступных на карту очков было ограничено: добавление более проходимых машин стоило больше, чем добавление более слабых. Игроку приходилось выбирать с умом, как он хочет страдать -- сильно или не очень.

== Я знаю, как срезать (всю игру)

В 2016 на игру начали поступать многочисленные жалобы, игроки сообщали о критическом баге, превращавшем игру в тыкву. Так называемый "часовой механизм" в коде игры через определённое время выводил её из строя и не давал играть. Кто-то считал, что сам Загребельный добавил вредоносный код в игру, но в ответ на обвинения Павел и студия в один голос твердили "это всего лишь меры борьбы с пиратством вышли боком".

Баг в итоге исправили, но с тех пор прошло много времени, и теперь Oovee абсолютно точно утверждает, что это и правда Павел добавил часовой механизм с целью отмщения. Более того, они обвиняют разработчика в "исправлении" ключевых функций: удаление из игры динамических кусков и мелких частичек грязи и воды, волн на воде, следов колёс на грунте и прочих отличительных черт игры.

И вот любительская технодемка уже на грани краха. Но крайним в скандале между разработчиком и студией оказалось сообщество, теряющее свою игру.

Но самая глубокая грязь ещё впереди, потому что тут на сцену вышел Saber. Как будто у игры и так было мало проблем.

== Здравствуй, Паша, я твой Сабер

В 2015 вдруг объявился Saber Interactive:

- А вы знаете, что ваша игра на самом деле принадлежит нам?
- Это почему?
- Потому что Павел разрабатывал Spintires, официально работая у нас, он использовал наши технологии и наш код без нашего разрешения. А ещё у него контракт, который гласит, что "Покуда Загребельный работает на Сабер, любой разработанный им игровой материал принадлежит Сабер".

Чтобы окончательно измазаться в грязи, компании подали друг против друга множество судебных исков. Мнение Павла никто не уточнял, а спустя некоторое время после начала споров о правах на игру, Загребельный сам вернулся под крыло Сабер. Как? Почему? Его простили? На этот счёт информации нет никакой.

Через годик, в августе 2016 компании немного уладили свои тёрки и пришли к соглашению: Saber не будет преследовать Oovee в суде за предположительно украденные ассеты и собственность, а Oovee оставит себе права на первую оригинальную версию Spintires, всю текущую и будущую прибыль с продажи игры. В ответ Saber ожидает право на публикацию консольных версий игры и любых "улучшений" для оригинальной игры, а также право получать с них прибыль, если будет делиться долей доходов с Oovee. Павла опять никто не спросил.

На какое-то время соглашение помогло. Сабер принялись за разработку тех самых улучшений и  в 2017 году выпустили Spintires: Mudrunneer. Хоть для игроков Spintires: Mudrunneer выглядела как новая игра, на бумаге и по коду это было всего лишь улучшение оригинальной спинки. Едва ли кто-то понял, что произошло и почему вдруг вышла вторая часть, которая по сути первая, но только улучшенная.

И тем не менее это был самый разумный выход из ситуации, позволявший избежать лишних неприятностей и новых скрытых часовых механизмов в коде. Игра официально вышла на ПК, Playstation и Xbox в октябре 2017, получив смешанные отзывы. Но, несмотря на все перипетии, фанаты серии были в восторге. И Сабер тоже. Ведь продажи шли очень хорошо: за год было продано более миллиона копий, а ещё через год, в 2018 был объявлен сиквел -- Snowrunner.

== Крути колёсами: грязебег

"Грязебег" по сравнению с "крути колёсами"  получил улучшенную графику и эффекты, а также впервые применил чудеса косметической хирургии на лицах. На грузовики впервые установили фейковые решетки радиатора, чтобы избежать проблем с лицензированием. Такой недостаток решили компенсировать количеством: вернули все когда-либо появлявшиеся в игре грузовики и добавили новые: КрАЗ 256, КрАЗ 260, КамАЗ 4310, Урал 375, КамАЗ 65115 (вместо 6520), ЗАЗ 968М, УАЗ 3141.

И не только грузовики! Кроме транспорта игра получила новые механики: блокпосты, которые не дают проезжать через город, возможность призвать скаут из любой точки, централизованная камера и вид из кабины. Но это было только начало, к выпуску планировалось ещё несколько дополнений с новыми картами и транспортом. А 27 ноября 2018 игра со всеми DLC вышла на Nintendo Switch.

Oovee, разумеется, не порадовал успех Mudrunneer. Релиз грязебега подлил масла в огонь спора, породив новую череду судебных исков, многие из которых не разрешены по сей день. Британская студия взяла пример с Паши, заявив, что "саблезубые" торчат им отчисления. Они даже запросили отчёт по выплатам, но получили шиш.

"Нет отчислений, нет контракта": Oovee решили продолжить обновлять оригинальную версию. Ситуация приобрела абсурдный характер: Saber отвечает за разработку Mudrunneer и грядущего Snowrunner, одновременно конкурируя со Spintires, которая является частью серии, но принадлежит другой студии.

В этот период Spintires чувствовала себя так-сяк. Игру то убирали из Steam, то снова возвращали. Но в 2019 "крути колёса" получила сразу несколько обновлений. Во-первых, появилось новое название и лого. Вместо "Spintires" игра стала называться "Spintires The Original Game". Также добавили пару грузовиков: новый КАМАЗ 4310, старый ЗИЛ 131, новый ЗИЛ 130. Во-вторых, улучшилась графика, появился дождь, изменилась физика грязи. +
В августе 2019 выпустили обновление Canyons DLC с новой картой и новым ЗИЛом Е-167 6x6. В октябре вышло первое платное обновление Aftermath DLC, включавшее в себя новую карту и два грузовика: ЗИЛ 133 Дизель 6x4 и ЗИЛ 133 Бензин 6x4. +
Декабрь принёс ещё одно обновление -- Чернобыль с картой и двумя грузовиками: МАЗ 505 4x4 и ЗИЛ 157 6x6, и новой механикой -- зонами радиации. Когда игрок проезжал через зоны радиации, его грузовик получал повреждение.

Ответный ход от Saber не заставил себя ждать. Они кинули претензию, и Spintires была удалена из магазина. Комментировать ситуацию отказываются как компании, так и сам Павел. То есть Павла вообще уже нет на арене, он залёг на дно и, может даже уже не работает в Saber.

Только один человек смог пролить свет на ситуацию -- бывший сотрудник Oovee и продюсер Spintires -- Рис Болтон. Рассказ Болтона ещё интереснее, чем всё, что было до сих пор.

== Море грязи

Рис Болтон пришёл в Oovee вскоре после основания компании. Он занимался мелкими проектами, а также добровольно исполнял обязанностями PR. В январе 2014 ему поручили создать внутреннюю команду разработчиков, а через несколько месяцев предложили в довесок стать продюсером Spintires.

Болтон плотно сотрудничал с Павлом при сознании игры и подтверждает версию о том, что студия не выплачивала весь причитающийся разработчику гонорар. По крайней мере так было до 2017, в апреле 2017 он ушёл из компании.

Болтон говорит, что нечестный бизнес и беспомощность перед юрлицом заставили Загребельного добавить часовой механизм в код игры. По версии продюсера, Павел мог использовать механизмы для борьбы с пиратством во вред с целью вымогательства денег.

Продюсер также заявляет, что основатель компании, Зэйн Сакстон не стремился инвестировать в новые разработки, а пустился во все тяжкие. В список покупок Сакстона попали: дом, две яхты, более 10 машин, включая несколько AMG, Ленд Роверов и пикапов Dodge SRT. Он также приобрёл ярмарочную карусель и транспортную компанию. По словам Болтона основатель компании положил на все долги, включая долги перед Павлом, и перевёл доход с продаж игры на счёт левой компании, чтобы скрыть следы.

Болтон подкидывает грязи в спор с Saber, утверждая, что Oovee не имела собственного штата разработчиков. Дескать студия разрешила Паше самому выбрать несколько помощников, почти все помощники работали в Сабер. Если это правда, то претензии о том, что Spintires использует код Saber без разрешения ещё более обоснованы.

По словам Риса, Сабер предоставили фрагмент своего закрытого движка, чтобы сравнить его код с кодом Spintires, и после сравнения код совпал на 100%.

При этом второй человек в Oovee, Девин Милсон, утверждал, что Сабер предъявляли претензии на пустом месте и не смогли предоставить никаких доказательств.

Так или иначе, ясно одно -- Сабер не собирались закрывать Oovee, они хотели урегулировать всё мирным путём: Сабер делают консольные версии и получают прибыль, платят процент, Oovee оставляют все наработки и полученные деньги -- по сути, это по факту и случилось.

Сакстон был рад мирному урегулированию, потому что деньги позволяли ему продолжать роскошную жизнь и не платить по счетам (всё предположительно, со слов других людей).

Ещё более жирный наброс от бывшего продюсера гласил, что Oovee ещё до заключения сделки с Saber передала публикационные права на консольные версии франшизы европейскому агентству IMGN.pro, забыв об этом упомянуть. После выхода Mudrunner Саблезубые получили дополнительную головную боль со стороны IMGN. Это предположение косвенно подтверждается недавними исками Saber и их утверждениями о том, что контакт был нарушен в 2018, ещё до его подписания.

Тогда Сабер поступили проще: удали префикс "Spintires" из названия "Mudrunneer" и отказались платить "алименты".

Тогда же Болтон ушёл из компании, назвавшись жертвой финансовых махинаций студии, которые могли или не могли иметь место. Он объяснил, что Oovee награждала его разными премиями, а потом попросили оформить с них нехилый налоговый вычет. В Британии такие схемы считаются за серую бухгалтерию.

== Скала, тупик, падение

До этого момента след более-менее прослеживался, были какие-то свидетели, а вот дальше... всё, что осталось журналистам на этой стадии -- следить за судебными разборками двух компаний. Ни один из исков не даёт ответов на самые важные вопросы жизни, и вселенной грязи. Почему Павел вернулся в Сабер? Почему Сабер его приняли? Почему Сабер совсем ничего не заплатили Oovee? И что же такое Oovee -- финансовая пирамида или студия по разработке игр, попавшая в трудную ситуацию?

Многое могли бы прояснить сами Saber, но они отказались от комментариев журналистам. Мол, всё ерунда, мы никому ничего не должны. И действительно, в 2020 Saber 3D стали частью компании Embracer и переименовались в Saber Interactive. Так что формально Saber Interactive или Embracer не были ответчиком ни в каких судебных исках. Но всем понятно, что это одни и те же люди, к тому же сей факт мешал "никак не связанной компании" подавать собственные иски к Oovee.

Что касается Павла, его не удалось найти ни по каким каналам связи. Он полностью растворился.

Основатель Oovee, Зэйн Сакстон, также затих где-то с августа 2018, когда Милсом присоединился к компании в роли директора по инвестициям. Эту должность он совмещал с YouTube каналом об инвестициях в серебро написанием книги по инвестициям в криптовалюту.

Да и сама студия Oovee постепенно растворяется. Никто из сотрудников или нанятых адвокатов не даёт никаких комментариев, сайт не работает как минимум с 2021. Компания увязла в долгах как в грязи: более миллиона фунтов стерлингов, а Spintires -- их единственная игра.

Где-то с начала 2020 начали расходиться слухи о сиквеле Мадраннера.

28 апреля 2020 года вышел Snowrunner. Изначально игра называлась Mudrunneer 2, но была переименована в "Снегобугуна" и выпущена на ПК, PS4, и Xbox One. Павел Загребельный участвовал в разработке как консультант.

Только за первый месяц игра разошлась тиражом в 1 миллион копий! Игрокам понравилось, что в игре теперь внушительный автопарк из североамериканских лицензированных грузовиков и отечественных, но не лицензированных. Машины можно "тюнинговать" и настраивать внешний вид под себя. Некоторые улучшения даются за прокачку уровня водителя, а другие нужно искать в открытом мире, где одна карта больше вместе взятые карты двух предыдущих игр. Игра уже три года получает пачки новых карт, грузовиков и прочих улучшений.

Карты больше не состоят только из грязи. Где-то есть асфальт, вода, снег, лёд и даже всё вместе.

Также в игре полностью изменилась графика: где-то лучше -- детализация, погода, рабочая кабина, зеркала, датчики, а где-то хуже -- грязь не липнет к колёсам как раньше. Зато есть подобие сюжета и огромное разнообразие грузов (по сравнению с только 1 грузом в предыдущих играх -- брёвнами). Но по коду это всё ещё улучшение Spintires.

Колёсики-то крутятся

Чем закончится история, пока сказать сложно, зато можно сказать, что с тракторами. В сентябре 2021 года Saber подали в суд на Oovee за незаконное использование трактора Кировец К-700. Они заявляют, что являются эксклюзивным владельцем прав на использование этого трактора в видеоиграх. Компания подписала контракт с производителем 29 декабря 2020 года. Но Oovee посмела использовать Кировец в Spintires аж с 2015 и по сей день, соответственно, торчит денег. После долгих и нудных разбирательств суд постановил, что Сабер неправы и хотят слишком многого. Кроме тракторов компании спорят о том, кому принадлежит музыка в Spintires и других немаловажных темах.

Так или иначе, однажды судебные процессы завершатся, но ни одна сторона не сможет назвать себя победителем, потому что все уже порядком измотаны. Лучшим исходом будет частная договорённость, которая устроит обе стороны, говорит эксперт по праву, Микаэла Мантегна из Berkman Klein Center Harvard Affiliate. Юристы стоят денег, которые можно было бы вложить в разработку новых более качественных игр.

Впрочем, Oovee и Spintires мы уже вряд ли когда-либо увидим. Спустя примерно полгода после выхода "Чернобыля", в игру добавили набор новых грузовиков. Затем вышло обновление с Шерпом. Вместе с появлением Шерпа -- первого лицензированного автомобиля, игра получила систему подкачки шин, которой нет сейчас ни в одной игре серии. В декабре 2020 игра получила последнее обновление -- "China Adventure". Новый азиатский регион с азиатскими автомобилями. Снова что-то так желанное игроками, чего нет ни в одной игре серии. Вскоре после выхода дополнения игру убрали из каталога Steam.

С тех пор компания уволила весь штат разработчиков, прекратила всякую активность, кроме судебной и существует за счёт остаточных средств от продажи единственной игры.

Saber же вполне успешно продаёт улучшения оригинальной игры: как Mudrunneer, который вышел также на мобильных устройствах, так и Snowrunner с мешком платных DLC-карт и грузовиков (и не меньшим мешком багов). Спустя год после эксклюзивного для Epic Game Store релиза Snowrunner  вышел в Стим и на Nintendo Switch, и получил Next Gen patch. Сейчас идёт третий год обновлений и дополнений (которые нередко ломают то, что работало). В Snowrunner Играет уже более 10 миллионов человек, скоро планируется добавить поддержку кросс-сейвов на всех платформах и другие улучшения.

Такова история одной игры, родившейся из простой любви одного человека к грузовичкам в грязи. Случайность, породившая целую франшизу, которая едва ли сделала разработчика счастливым или очень богатым. Такое ощущение, что в истории больше всего разбогатели юристы, а игроки, как всегда, остались крайними.

Материал основан на большой статье с https://www.ign.com/articles/stuck-in-the-mud-how-a-tiny-beloved-driving-game-sparked-a-bizarre-decade-long-feud[сайта IGN.com], видео от https://www.youtube.com/channel/UCwqffkG2hE09XcrAchf8gGA[nprovince], https://www.youtube.com/channel/UC9qwsLyhcbGI8rlbSqH6o7A[maxpower5205] и https://www.youtube.com/@SD1ONE[SD1ONE], а также личных наблюдениях.

#snowrunner #spintires #mudrunner
