= Заголовок

Кражи ассетов, пропавшие разработчики: как появился на свет Snowrunner

Нас всех объединяет любовь к сгегобегу-глиномесу, кто-то даже играл в Spintires и Mudrunner и считает, что это должна была быть одна игра. В этой детективной истории расскажу, как небольшое хобби одного человека переросло в серию игр.

Начало, конечно, было положено в Spintires. Первая демка была выпущена в 2009 году. Это был проект одного парня по имени Павел Загребельный. На тот момент Павел официально работал в Saber Interactive. Помимо основной работы у Павла были другие интересы: DirectX9, пляжные виды спорта и красивые женщины. Но один интерес тянулся из детства - игры с игрушечными грузовичками. Это было просто хобби, он делал демку Spintires уже несколько лет в свободное время. Автопарк в первой версии состоял из двух грузовиков Краз 255 и КамАЗ 6460. Оба грузовика были точными копиями своих реальных прототипов и даже имели настоящие логотипы на решётке радиатора.

Павел представил первую версию Spintires на конкурсе Intel Level Up и внезапно выиграл приз за лучшие показатели производительности на многоядерных процессорах и второй приз за лучшую оптимизацию под графику Intel. Все хвалили игру за уникальную физику деформации грязи. Победа и доселе невиданные механики привлекли внимание Oovee - маленькой независимой компании из Соединённого королевства.

Oovee появилась только год назад и была сосредоточена на выпуске дополнений для серии Train Simulator. Представители компании остались под впечатлением от первой "демо-спинки" и предложили опубликовать его на своём сайте. Павел принял предложение.

Демка была востребована и в 2011 году Пашу попросили принять участие в разработке полноценного релиза. Парень стал работать на Oovee в качестве консультанта, одновременно будучи устроенным в Saber. Тогда же вышла очередная версия игры. На этот раз элементы итогового оверлея были немного переработаны, а грузовиков стало уже пять: КРАЗ 255 6x6, КамАЗ 5460 4x2 тягач, КамАЗ 6460 6x4 тягач, КамАЗ 6522 тягач в трёх вариантах и КамАЗ 65228 8x8 тягач. Это была всё ещё технодемка, но включала сразу 7 карт.

Взаимовыгодное сотрудничество продолжалось несколько лет, пока в 2013 студия не решила вывести игру на кикстартер, собрав без малого 61 тысячу евро. В этой версии была только одна машина - МАЗ 535. Дифференциал и полный привод подключались отдельно по команде. В игре появился цикл дня и ночи и более красивая графика. Чуть позже был добавлен маленький скаут - УАЗ 469 и возвращён КРАЗ 255. Примерно тогда же Загребельный решил уйти из Сабер, чтобы сосредоточиться всеми силами на своём проекте. На следующий год Spintires официально вышла в Стим. Это был феноменальный успех. Спинка на время стала самой продаваемой игрой на платформе, 100 000 копий было продано только за первые 18 дней.

В релизе был целый автопарк: КамАЗ 6522 (вместо 6x4), УАЗ 469 (редизайн), МАЗ 537 (вместо 535), ЗИЛ 130 (новый), Урал 432010 (новый), МАЗ 7310 (новый огромный 8x8). Для грузовиков добавлены разнообразные модули и возможности тюнинга. Это уже было в предыдущих версиях, но а релизе выбор был гораздо богаче. Появились разные колёса с разными характеристиками и несколько полноценных карт, лебёдка и перевороты.

Но чем выше ты взбираешься, тем больнее падать. Неожиданный успех привлёк внимание и до сих пор давит весом пачки металлических балок на будущее серии.

По грязи на повышенной

На момент появления Spintires Oovee имела стоила примерно 14 000 долларов. За год с момента релиза игры компания стала стоить почти 1,4 миллиона долларов. Следующий год был ещё лучше. Основатель компании на радостях купил себе Мерс за 165 тысяч баксов (который ему через две недели облили растворителем), открыл несколько бизнес-предприятий.

Примерно в это же время, с 2014 по 2016, золотой разработчик начал жаловаться в соцсетях на то, что работодатель платит вообще-то не всю оговоренную долю с продаж.

Павел писал на своей странице ВКонтакте о том, что он закончил редактор модов, новый бесплатный DLC для игры, но англичанин из Oovee пропал вместе с деньгами и закрыл доступ в Стим. Павел выпустил редактор карт для текущей версии и назвал это концом Spintires.

А сколько студия должна была отдавать разработчику? Ровно половину доходов с продаж! Минус налоги и прочие расходы. Точных свидетельств о том, сколько получал разработчик игры нет, как нет и точного дохода от продаж "Спинки". Студия же отрицала все обвинения, говоря, что платили разработчику в полном объёме.

Игроки не знали, что происходит за кадром, но могли свидетельствовать закат игры: через год после запуска обновления постепенно заселились и прекратились вовсе, игра изобиловала багами и отсутствующими функциями.

Но это не значит, что игра совсем не получала обновлений. Были как маленькие исправления, так и полноценные DLC. Первое большое обновление принесло в игру новую карту "Наводнение" и несколько грузовиков: КамАЗ 6520 (он вернулся), ЗИЛ 131, Кировец К700 (ещё отзовётся эхом в Snowrunner), Урал 4320, МАЗ 535 (вместо 537, который только на релизе появился; серьёзно, зачем было их так тасовать?).

Другое большое обновление в районе 2015 добавило в игру 1 новый грузовик: ГАЗ 66 и удалило два старых: Урал 432010 и совсем свежий ЗИЛ 131. Все остальные грузовики получили обновленные модельки: больше детализации, анимация водителя, анимированные механизмы карданных валов и т.д. Это было то самое обновление, которое должно было символизировать занавес над игрой, именно в нём появилась поддержка модов. Кроме того появилась система очков баланса, которая позволяла выбирать грузовики перед началом карты в зависимости от доступных очков баланса. Общее число доступных на карту очков было ограничено: добавление более проходимых машин стоило больше, чем добавление более слабых. Игроку приходилось выбирать с умом: страдать сильно или не очень.

В 2016 по следам многочисленных жалоб со стороны сообщества был найден критический баг, который превращал игру в тыкву. Так называемый "часовой механизм" в коде игры должен был через определённое время выводить её из строя. Кто-то считал, что это сам Загребельный добавил вредоносный код в игру, но что Павел что студия в один голос твердили, что это всего лишь меры борьбы с пиратством вышли боком.

Баг в итоге исправили, с тех пор прошло много времени, и теперь Oovee абсолютно точно утверждает, что это и правда Павел добавил часовой механизм с целью отомстить. Более того, они обвиняют разработчика в "исправлении" не только багов, но и ключевых функций: динамические куски грязи, волны на воде, мелкие частички грязи и воды, следы колёс на грунте и другие отличительные черты игры.

Таким образом любительская технодемка оказалась на грани краха, а ни в чём неповинное сообщество оказалось крайним в скандале между разработчиком и студией.

И тут на сцену вышел Saber.

Здравствуй, Паша, я твой Сабер

Как будто у игры было мало проблем, но в 2015 вдруг объявился Saber Interactive:

- А вы знаете, что ваша игра на самом деле принадлежит нам?
- Это почему?
- Ну, ваш разработчик официально работал у нас, использовал наши технологии и наш код без разрешения. А ещё его контракт гласит, что любой игровой материал принадлежит нам, покуда он работает у нас.

Компании подали друг против друга множество судебных исков, но при этом мнением самого Павла никто не интересовался. Спустя некоторое время после начала споров о том, кому же всё-таки принадлежит игра Загребельный сам решил вернуться под крыло Сабер.

В августе 2016 компании наконец пришли к соглашению: Saber не будет преследовать Oovee в суде за предположительно украденные ассеты и собственность. Oovee оставит себе права на первую оригинальную версию Spintires, оставит себе всю полученную с игры прибыль, полученную до этого момента и любую будущую прибыль. В ответ Saber получает право на публикацию консольных версий и любых "улучшений" для оригинальной игры, получать с них прибыль, пока будет делиться долей дохода с Oovee. Павла опять никто не спросил.

Соглашение помогло снять напряжение на какое-то время. Сабер выпустили Spintires: Mudrunneer - "улучшение" для оригинальной игры. Едва ли кто-то понял, что произошло и почему вдруг вышла вторая часть, которая по сути первая, но только улучшенная.

Это был самый разумный выход из ситуации - способ избежать потенциальных часовых механизмов в коде и лишних неприятностей. Игра Spintires: Mudrunneer официально вышла на ПК, Playstation и Xbox в октябре 2017, получив смешанные отзывы, при этом версия для ПК была принята лучше. Но фанаты серии были в восторге. И Сабер тоже, ведь игра продавалась очень хорошо: за год было продано более миллиона копий. В 2018 был объявлен сиквел - Snowrunner.

По сравнению с оригинальнрй игрой "грязевой бегун" получил обновленную графику и эффекты, а также изменённую внешность машин. На грузовики ставили фейковые решетки радиатора, чтобы избежать проблем с лицензированием. Коме всех когда-либо появлявшихся в игре грузовиков были добавлены КрАЗ 256, КрАЗ 260, КамАЗ 4310, Урал 375, КамАЗ 65115 (вместо 6520), ЗАЗ 968М, УАЗ 3141. Кроме транспорта игра получила новые механики: блокпосты, которые не дают проезжать через город, возможность призвать скаут из любой точки, централизованная камера и вид из кабины. Но это было только начало. В планах было выпустить ещё несколько дополнений с новыми картами и транспортом. А 27 ноября 2018 игра вышла на Nintendo Switch со всеми DLC.

Oovee, разумеется, не порадовал успех Mudrunneer. Спор разгорелся вновь и вылился в череду судебных исков, не разрешённых по сей день. Британская студия взяла пример с Паши, заявив, что "саблезубые" торчат им отчисления. Они даже запросили отчёт по выплатам, но получили шиш.

Нет отчислений, нет контракта, Oovee решили продолжить обновлять оригинальную версию. Ситуация приобрела абсурдный характер: Saber отвечает за разработку Mudrunneer и грядущего Snowrunner, одновременно конкурируя со Spintires, которая является частью серии, но принадлежит другой студии.

А Spintires чувствовала себя так-сяк. Игру то убирали из Steam, то снова возвращали. Но в 2019 крутиколёса получила сразу несколько обновлений. Во-первых появилось новое название и лого. Вместо Spintires игра стала называться Spintires. The Original Game. Также добавили пару грузовиков: новый КАМАЗ 4310, старый ЗИЛ 131, новый ЗИЛ 130.  Во-вторых улучшилась графика, появился дождь, изменилась физика грязи.
Затем в августе 2019 пришло обновление Canyons DLC с новой картой и новым ЗИЛом Е-167 6x6. В октябре вышло первое платное обновление Aftermath DLC. Обновление включало в себя новую карту и два грузовика: ЗИЛ 133 Дизель 6x4 и ЗИЛ 133 Бензин 6x4.

Ответный ход от Saber не заставил себя ждать. Они кинули претензию и Spintires была удалена из Стим. Критиковать ситуацию компании отказываются, а Павел и подавно залёг на дно. Работает ли он на Saber - остаётся загадкой.

Только один человек смог пролить свет на ситуацию - бывший сотрудник Oovee и продюсер Spintires - Рис Болтон. История Болтона ещё более невероятная, чем всё, что было до сих пор.

Другая сторона Oovee

Рис Болтон пришёл в Oovee вскоре после основания компании. Он занимался мелкими проектами, а также добровольно занимался обязанностями PR. В январе 2014 ему поручили создать внутреннюю команду разработчиков, а через несколько месяцев предложи в довесок стать продюсером Spintires.

Болтон плотно сотрудничал с Павлом над сознанием игры и подтверждает версию о том, что студия не выплачивала весь причитающийся разработчику гонорар, по крайней мере так было до 2017. Болтон ушёл из компании в апреле 2017.

По предложениям Болтона невыплаты и неспособность ответить заставили Загребельного добавить часовой механизм в код игры. По версии продюсера Павел мог использовать встроенные механизмы для борьбы с пиратством как способ затребовать выплаты.

Болтон также заявил, что основатель компании, Зэйн Сакстон не стремился инвестировать в новые разработки, а вместо этого пустился во все тяжкие. Список покупок Сакстона составляли: дом, две яхты, более 10 машин, включая несколько AMG, Ленд Роверов и пикапов Dodge SRT. Он также приобрёл ярмарочную карусель и транспортную компанию. По словам Болтона основатель компании положил на все долги, включая долги перед Павлом, и направил доход с продаж игры на счёт левой компании, чтобы скрыть следы.

Болтон подливает масла в споре с Saber, он утверждает, что Oovee не имела собственного штата разработчиков, с разрешения работодателя Павел сам нанял несколько помощников. Почти все они работали в Сабер. Если это правда, то претензии о том, что Spintires использует код Saber без разрешения совсем не беспочвенны.

По его словам Сабер предоставили фрагмент своего закрытого движка, чтобы сравнить его код с кодом Spintires, и после сравнения код совпал на 100%.

Второй человек в Oovee, Девин Милсон, утверждал, что Сабер предъявляли претензии на пустом месте и не смогли предоставить никаких доказательств.

Так или иначе, ясно одно - Сабер не собирались закрывать Oovee, они хотели урегулировать всё мирным путём: они делают консольные версии и получают прибыль, платят процент, Oovee оставляет все наработки и полученные деньги - то, что по факту и случилось.

Сакстон был рад такому развитию событий, потому что так он мог продолжить роскошную жизнь и не платить по счетам (всё предположительно, со слов других людей).

Болтон не стеснялся в раскрытии правды, по его словам Oovee ещё до заключения сделки с Saber передала публикационные права на консольные версии франшизы европейскому агентству IMGN.pro и забыла об этом упомянуть. В результате после выхода Mudrunneer саблезубые получили от IMGN множество исков. Это утверждение косвенно подтверждается недавними исками Saber и их утверждениями о том, что контакт был нарушен в 2018, ещё до него подписания.

Тогда Сабер поступили проще: удали префикс Spintires из названия Mudrunneer и отказались платить "алименты".

Тогда же Болтон ушёл из компании, назвавшись жертвой финансовых махинаций студии, которые могли иметь место. Он объяснил, что Oovee награждала его разными премями, которые оформили как разработку игры по контракту. С такой деятельности в Британии полагается большой налоговый вычет, который студия попросила Болтона оформить. Короче, студия не только задолжала Павлу за его работу, но ещё и проворачивала серые налоговые схемы.

И они испарились

На этом чёткие следы закончились, всё, что осталось журналистам на этой стадии - следить за судебными разборками двух компаний. Но ничто не даёт ответов на самые важные вопросы жизни, и вселенной франшизы. Почему Павел вернулся в Сабер? Почему Сабер его приняли? Почему Сабер не заплатили Oovee ничего? И что же такое Oovee - финансовая пирамида или студия под разработке игр, переживающая тяжёлые времена?

Многое могли бы прояснить сами Saber, но они отказались от комментариев журналистам. Мол, всё ерунда, мы никому ничего не должны. И действительно, в 2020 Saber 3D стали частью компании Embracer и переименовались в Saber Interactive. Так что формально Saber Interactive или Embracer не были ответчиком ни в каких судебных исках. Но всем понятно, что это одни и те же люди, к тому же сей факт мешал "никак не связанной компании" подавать собственные иски к Oovee.

Что касается Павла, его не удалось найти ни по каким каналам связи. Он полностью растворился.

Основатель Oovee, Зэйн Сакстон, также затих где-то с августа 2018, когда Милсом присоединился к компании в роли директора по инвестициям. Эту должность он совмещал с YouTube каналом об инвестициях в серебро написанием книги по инвестициям в криптовалюту.

Да и сама студия Oovee постепенно растворяется. Никто из сотрудников или нанятых адвокатов не даёт никаких комментариев, сайт не работает как минимум с 2021. Компания увязла в долгах как в грязи: более миллиона фунтов стерлингов, а Spintires - их единственная игра.

Колёсики-то крутятся

Чем закончится история, пока сказать сложно, зато можно сказать, что с тракторами. В сентябре 2021 года Saber подали в суд на Oovee за незаконное использование трактора Кировец К-700. Они заявляют, что являются эксклюзивным владельцем прав на использование этого трактора в видеоиграх. Компания подписала контракт с производителем 29 декабря 2020 года. Но Oovee посмела использовать Кировец в Spintires аж с 2015 и по сей день, соответственно, торчит денег. После долгих и нудных разбирательств суд постановил, что Сабер неправы и хотят слишком многого. Кроме тракторов компании спорят о том, кому принадлежит музыка в Spintires и других немаловажных темах.

Так или иначе, однажды судебные процессы завершатся, но ни одна сторона не сможет назвать себя победителем, потому что все уже порядком измотаны. Лучшим исходом будет частная договорённость, которая устроит обе стороны, говорит эксперт по праву, Микаэла Мантегна из Berkman Klein Center Harvard Affiliate. Юристы стоят денег, которые можно было бы вложить в разработку новых более качественных игр.
