= Заголовок

[#slide1]

Привет всем, меня зовут Маркиев Владимир, я технический писатель в компании Docsvision. Я расскажу про нашу новую онлайн документацию, её возможности и расширяемость.

[#slide2]
== Устройство

Документация построена при помощи генератора статических сайтов Antora. Antora позволяет создавать сайты документации на основе HTML, CSS и JavaScript.

Исходный формат документации -- файлы AsciiDoc, которые я создаю и размещаю в разных репозиториях, указываю ссылки на источник в месте, где Antora сможет их найти и запускаю сборку. Преимущество такого подхода в разделении исходных файлов и конечных, мне практически не нужно вмешиваться во внешний вид сайта и работать с его компонентами.

[#slide3]
Простой и одновременно функциональный язык разметки AsciiDoc позволяет мне не волноваться о форматировании или перекрёстных ссылках. Файлы формата AsciiDoc -- это текстовые файлы, которые могут быть открыты в любом редакторе в любой файловой системе, а значит каждый может их редактировать. Чтобы понять базовый синтаксис, достаточно сравнить исходный текст с результатом на сайте.

[#slide4]
== Структура документации

Краткий итог того сказанного выше: я пишу исходный код документации в формате AsciiDoc, отправляю файлы в GitHub, эстафету перехватывает Antora, она собирает файлы и создаёт сайт с документацией.

Мы храним исходные файлы в репозитории на GitHub и используем утилиты для редактирования. Этот подход называется "docs as code" -- хранение документации в репозитории в виде кода. Таким образом при разработке документации можно пользоваться теми же инструментами, что и при разработке продукта.

[#slide5]
На более глубоком уровне Antora использует проект пользовательского интерфейса -- веб-шаблоны, отвечающие за внешний вид сайта. Проект пользовательского интерфейса также хранится в репозитории на GitHub.

[#slide6]
На пользовательском интерфейсе остановлюсь чуть подробнее. Структура представлена на слайде. Необязательно использовать стили и структуру по умолчанию, всё можно настроить под себя:

* Поменять стили, отредактировав файлы CSS
* Добавить собственные скрипты, меняющие поведение элементов на странице
* Изменить порядок элементов на странице и ссылки в шапке

Если вы знакомы с разработкой сайтов, вам будет легко понять принципы работы с файлами пользовательского интерфейса. Это как редактировать обычный HTML, только по окончании работы нужно собрать архив, который будет использован при запуске Antora.

Инструкция по работе с пользовательским интерфейсом приведена в README https://github.com/Docsvision/antora-ui-default[репозитория на GitHub].

[#slide7]
== Репозитории документации

Сайт документации состоит из нескольких компонентов. Основной компонент -- репозиторий antora-playbook. В нём расположена конфигурационный файл сайта -- файл `antora-playbook.yml`. Конфигурационный файл содержит инструкции, сообщающие Antora, как собирать сайт, а также все ссылки на другие компоненты.

Antora поддерживает работу с множественными репозиториями, поэтому каждый раздел нашей новой документации -- это отдельный репозиторий. Каждый модуль нашей системы -- это компонент сайта, каждая версия модуля -- отдельная ветка в репозитории.

Все репозитории документации объединяет то, что у них в названии есть `Antora`. Перейдите в профиль https://github.com/Docsvision?q=antora&type=all&language=&sort=[Docsvision на GitHub] и найдите репозитории со словом Antora в названии.

Вы можете сделать свою копию любого репозитория и изменить содержимое на любой странице сайта.

Стандартная структура компонента с документацией представлена на слайде.

== Демо

Подробнее, как это делается я объясню в практической части.

Допустим, вы добавили расширение для нового грида в Web-клиенте, расширение представляет собой новый элемент управления, который добавляется внутрь панели инструментов.

. Клонируем репозиторий Web-клиента.
. Вспоминаем, что грид -- это элемент управления, а значит нам нужна документация конструктора разметок.
. Находим нужную папку, в данном случае полный путь будет такой: menu:Корень репозитория Web-клиента[Служебная папка "модули" > layouts -- то есть конструктор разметок > ctrl -- папка с документацией элементов управления > folderComponents -- группа элементов управления нового грида].
+
`WebC-Antora/modules/layouts/pages/ctrl/folderComponents/`
+
. Открываем файл `folderGrid_FolderGridToolbar.adoc`.
. AsciiDoc можно открыть в любом текстовом редакторе, но мы рекомендуем использовать бесплатную программу IntelliJ Idea Community Edition с плагином AsciiDoc.
. Получить справку по синтаксису AsciiDoc можно на официальном сайте https://docs.asciidoctor.org/. После редактирования отправьте изменения в git, командами git commit, git push.
. Откройте antora-playbook.yml и подмените адрес репозитория Docsvision на собственный.
. Запустите Antora командой `npx antora antora-playbook.yml`.
. Посмотрите изменения на странице сайта в браузере: `antora-playbook/wwwroot/webclient/5.5.17/layouts/ctrl/folderComponents/folderGrid_FolderGridToolbar/index.html`
. Подробная инструкция по работе с сайтом документации приведена в README https://github.com/Docsvision/antora-playbook[репозитория antora-playbook] в профиле Docsvision на GitHub.

== Примерный план

50 - как устроена (антора, репозитории)
50 - как можно расширять (свои решения)

Пара-тройка вопросов на конкурс
