= Готовь сани летом, а лонгборд зимой. Помогаю с выбором.

Средства индивидуальной мобильности давно и плотно вошли в нашу жизнь, но мне не нравятся самокаты, велосипед негде хранить, а вот доска на колёсах - то, что надо. Расскажу про историю развития культуры и все тонкости выбора досок.

Снег на улице всё ещё лежит, значит можно сказать "зимой".

== Что такое лонгборд и чем отличается от скейтборда?

Основное отличие - размеры, лонг обычно больше скейта, он не рассчитан на выполнение трюков, а создан, чтобы получать удовольствие от езды.

Лонгборды более дружелюбны к новичкам, т.к. имеют более низкий центр тяжести. Дека (доска) лонгборда обычно длиннее чем у скейтборда, шире и ниже. Научиться ездить на большой доске значительно проще, нежели на маленькой. Колёса лонгов тоже обычно крупнее, шире и мягче чем у скейта.

История роликовых досок начинается примерно в 1950х годах в Калифорнии. Сперва это были изобретения энтузиастов - в буквальном смысле роликовые доски, то есть доски к которым приделали колёса от роликов. Колёса для роликов в то время изготавливали из стали или "композитной глины": смеси из пластика, бумаги и перемолотой скорлупы грецкого ореха.

Едва ли это было безопасное изобретение, едва ли оно было популярно. Но по задумке это была альтернатива сёрфингу, когда в океане нет волн; свою функцию эти доски выполняли.

Первые серийные лонгборды появились в '59 году. Это всё ещё были очень сырые изобретения на стальных колёсах. Безопасность? Нет, не слышали. Мало кто оценил такие игрушки, поэтому к середине 60-х о них уже успели забыть все, кроме хардконых фанатов.

Новая волна популярности лонгбордов наступила с изобретением полиуретановых кодёс в 1972. Фрэнк Нэшворти и компания Cadillac Wheel Company. Фрэнк переехал в Калифорнию и обратил внимание на неуклюжие попытки местных ребят кататься на роликовых досках, когда погода не располагает к серфингу. Он решил поэкспериментировать с новым материалом. Фрэнк попросил у отца своего знакомого 10 комплектов полиуретановых колёс и решил поэкспериментировать, предполагая, что более мягкие колёса из полиуретана дадут большее сцепление с поверхностью и помогут новичкам.

После проверки оказалось, что новые колёса ещё и едут значительно лучше, позволяют легче управлять доской и лучше поглощают неровности.

Парня так впечатлило его открытие, что он вложил все свои сбережения (700 долларов, накопленные от работы прислугой в ресторане) в новую компанию Cadillac Wheels Company, потому что Кадиллак - это синоним комфорта.

Сперва бизнес не шёл, приходилось напрямую продавать колёса в магазины для сёрферов. Но когда слухи о новом изобретении распространились достаточно широко, это произвело настоящий фурор и привело к возрождению культуры скейтбординга. К 1975 году Нэшворти продавал по 300 000 комплектов колёс в год.

Затем Нэшворти решил продать лицензию на свои колёса производителю скейтоа под названием Bahne and Co., которые начали продавать по 10-20 тысяч досок в месяц. Новые колёсики совершили революцию в мире скейтбординга, но успех длился недолго.

Вскоре случился новый бум, связанный с открытием колёсных подшипников.
В 1984 Нэшворти закончил бакалавриат по механике и начал работать инженером в Hewlett Packard, где он участвовал в разработке первого широкоформатного струйного принтера. Он работал в D&K Engineering, затем в Simplexity Product Development, откуда ушёл на пенсию в 2017 году.

Ещё одна важная веха в истории уже исключительно лонгбординга - изобретение подвески вида reverse kingpin, позволявшей занизить высоту деки. Таким образом удалось добиться большей стабильности и гибкости. Благодаря колёсам, подшипникаи и подвеске родилось целое спортивное направление - downhill longboarding, когда длинные доски используют для скоростного спуска с горы.

В 90-х додумались использовать вырезы на досках под колёсные арки, что избавило от соприкосновения колёс с декой.

Современные лонгборды отличаются от скейтбордов.  Скейт создан в первую очередь для трюков. Логборд едет плавно, ровно и далеко, плавными волнообразными движениями он наиболее похож на доску для сёрфинга.

****
Стоимость лонгбордов в сборе в спортивных магазинах начинается от 5 тысяч рублей. Это будет самый простой пластиковый детский лонгборд. Более-менее приличный лонгборд для взрослого человека будет стоить от 7 тысяч.

https://www.kant.ru/catalog/skateboards-longboards/longboardy/#/filter:sort=price&order=desc&pr_8477=ekspert&

В специализированных магазинах стоимость только деки может начинаться от 10 тысяч.

https://justx3m.ru/brand/Loaded%20Longboards/?sort=price&order=asc

На цену влияет состав деки -- качество древесины, количество слоёв дерева, уровень премиальности комплектующих и даже раскраска. Если доску раскрасил известный в узких кругах художник, она будет стоить дороже.

****

Кто-то предпочитает просто кататься, из точки А в точку Б, для этого подойдёт любая доска. Но на лонгборде можно ездить очень далеко, для таких экспедиций лучше всего подходят drop-through и/или drop deck. Такие доски имеет более низкий центр тяжести и более твёрдые катки (колёса), соответственно ездок тратит меньше усилий на поддержание равновесия и дольше катится по инерции после толчка. В катании нет никакой тонкости или сложности - ездок встаёт на доску, отталкивается и едет.

Но это ещё не значит, что на лонгборде нельзя получать удовольствие и веселиться. Существует много разных дисциплин, помните?

== Виды катания

Лонгборды выглядят по-разному в зависимости от дисциплины ездока: даунхилл, слалом, фрирайд, танцы или фристайл.

Карвинг или вырезание узоров - простая техника переноса веса тела так, чтобы удачнее выполнять крутые повороты. Техника может быть самостоятельной, а может быть частью других дисциплин. Доска для карвинга должна иметь более высокий центр тяжести и хорошую маневренность. Обычно пинтейл средней длины или аналоги.

Даунхилл - вот, где настоящее веселье. Подразумевает езду на высоких скоростях с больших склонов. Для даунхилла используют жёсткие доски, которые предотвращают любые помехи из-за изгибания деки. Подходят только доски с наиболее низким центром тяжести: dropped, drop-through и прочие низкопрофильные.

Кстати, а насколько большие скорости? Самая высокая зарегистрированная скорость (мировой рекорд) была установлена в 2017 году и составляла 91.17 км/ч.

Стоит ли говорить, как опасен этот вид катания и как легко можно сломать голову или шею?

Фрирайд - разновидность даунхилла, но на более спокойных скоростях.

Фристайл или делай, что хочешь насколько тебе позволяет твоя креативность. Главная тема фристайла - показать свои умения. Часто используются трюки, заимствованные у скейтеров, поэтому доска обычно имеет симметричную форму, чтобы было удобно крутить, вертеть и подбрасывать.

Для понимания трюков нужно учитывать габариты - обычно используют деки средней или максимальной длины.

Некоторые ездоки умудряются вытворять танцы на доске: шаги, повороты, развороты, кручения и всё это на ходу, пока доска катится. Естественно, для танцев на доске требуется место, так что доски обычно используются длинные и устойчивые.

****
В зависимости от дисциплины стоимость доски в сборе тоже будет разная.
Доска для даунхилла и фрирайда будет нести в себе наиболее технологичные решения, соответственно, стоит будет дороже.

https://www.kant.ru/catalog/product/1792037/

Доски для катания в танце тоже стоят дорого, потому что от них требуется быть прочными и мягкими одновременно.

https://www.kant.ru/catalog/product/2939277/
****

Дальше расскажу подробнее о компонентах лонгборда, влияющих на качество и характеристики доски.

== Дека

В первую очередь - это дека, сама доска, на которая принимает вес ездока. Доски делают из тонких слоёв дерева, обычно клёна, дуба, берёзы или дуба.

Простого куска дерева недостаточно, толщина стандартного слоя - 2 мм и таких слоёв может быть от 2 до 11. В зависимости от используемого дерева и количества слоёв доска будет жёстче или мягче. Например, для даунхилла берут максимально жёсткие и лёгкие деки, соответственно, добавляют слои.

Пластиковые деки обычно не используют - это не канон, а вот карбоновое и стекловолокно вполне подойдёт как усилитель или замена для дерева, но стоимость такой деки будет заоблачная.

****
Стоимость композитной деки из дерева с примесью стекловолокна начинается от примерно 20 тысяч рублей.

https://www.traektoria.ru/product/725101_deka-longbord-loaded-dervish-sama-deck-flex-2/
****

=== Длина деки

Деки принято различать по форме и длине. Каждому стилю катания больше всего подходит определённая форма и длина доски.

В первую очередь нужно определиться с длиной. Длину считают в дюймах, но для наглядности переведу в сантиметры.

Длина деки варьируется от 33 до 59 дюймов (84 - 150 см), а ширина от 8.5 дюймов до 9.8 (22.8 - 25.4 см).

- Короткая дека будет иметь длину деки 36 дюймов или меньше - 91.44 см.
- Средней (половиной) длиной считается 40-дюймовая дека - 101 см.
- Наконец, длинная дека будет иметь длину 42 дюйма и больше - 106.67 см.

****
Короткие деки стоят дешевле по очевидной причине - на них требуется меньше материала. Стоимость приличной короткой деки будет в районе 7-10 тысяч

https://www.traektoria.ru/longboards/deka/?SIZE=26%2C5%7E30%7E33%2C5%7E34%2C0%7E36X9%2C25

Дека средней длины из обычного дерева может стоить от 10 тысяч. Если в составе есть композитные материалы, стоимость может возрасти в два раза и больше.

https://www.traektoria.ru/longboards/deka/?SIZE=38%2C75%7E39%7E39%2C5%7E40%7E41%2C125

Дека полной длины обанкротит вас так же примерно на +/- 10 тысяч рублей.

https://www.skatepro.ru/c208.htm
****

У длинных досок есть главное преимущество - на них легче удержатся. В недостатки можно записать плохую манёвренность, большой вес и громоздкость. Их тяжелее носить с собой и сложнее хранить в доме.

Средняя длина деки подходит для большинства задач и стилей катания, но из-за своей универсальности может проигрывать более специализированным вариантам.

Короткие доски наиболее управляемые и наименее устойчивые. Исправляют все недостатки длинных, но плохо подходят для новичков и большинства стилей катания.

=== Форма деки

По форме различают следующие деки:

- pintail - пинтейл, задняя часть доски похожа на утиный хвост. Такая форма позволяет избежать "закусывания" задних колёс, но не позволит выполнять многие трюки и лишит части функционального пространства. Подходит для неспешного катания без особой цели https://www.traektoria.ru/product/1320054_deka-longbord-sector9-maverick-stack-deck/
- swallowtail - доска по форме напоминает ласточкин хвост. Примерно то же самое, что и пинтейл, но с небольшими отличиями в виде более высокой стабильности. https://justx3m.ru/longbordy/deki/deka-longbord-kebbek-emily-pross-city/
- flat-nose - передняя часть доски более округлой формы https://www.kant.ru/catalog/product/1653343/
- drop-down/drop deck - когда дека имеет "ступеньку" посередине. Это очень стабильные и обычно упругие доски, на них невозможно выполнять трюки, зато очень легко начать ехать и набрать скорость особенно с горки. https://www.traektoria.ru/product/725101_deka-longbord-loaded-dervish-sama-deck-flex-2/
- киктейл - доски обычной скейтбордной формы. Киктейл может быть один или два. Это просто скруглённый край, который удобно "пинать". Позволяет лучше контролировать движения и демонстрировать трюковые навыки. Двойной киктейл будет выглядеть симметрично со всех сторон, так что можно не переживать за то, с какой стороны встать и куда ехать. https://justx3m.ru/longbordy/deki/longbord-deka-pepper-boards-bastet-special/
- дансер - дека для танцоров. Очень мягкая, очень гибкая и очень длинная дека, на ней можно крутиться как угодно, ходить из конца в конец и делать всё, что угодно. Только скорости от такой доски не дождёшься. https://www.skatepro.ru/208-34448.htm?stockcode=YDEC20FREMICFIBMED

Ещё один нюанс при выборе деки - это конкейв или прогиб.  Простым словами - это форма доски в профиль, со стороны. Прогиб бывает трёх видов:

- Кембер - когда профиль доски выпучен горбом. Такой профиль отлично подходит для маневров в общем, и карвинга в частности. Когда ездок прижимает доску своим весом к земле при повороте, а потом переносит вес при выходе из поворота, доска сама докручивает маневр.
- Рокер - прогиб, напоминающий букву U. Когда доска уже немного вогнута, ездок получает дополнительную стабильность и стоит немного увереннее. Такой прогиб отлично подходит для новичков.
- Флэт - просто плоская доска. Такие делают редко, либо в гаражах на собственном оборудовании, либо поклонники ретро-стиля, ведь в самом начале истории лонгбордов никакого прогиба и не было.

https://longboardmania.ru/stati/vidy-longbrdov-i-ih-osobennosti/

Также дека имеет поперечный прогиб - форма места, на которое ездок ставит ноги. Тоже бывает разных видов. Самый распространённый - U-образный. Чем глубже поперечный прогиб, тем удобнее стоять на доске ногами, он фиксирует стопу и даёт больше уверенности. Но слишком большой прогиб лишает возможности маневрировать. Глубокий поперечный прогиб используется на досках для даунхилла и его разновидностей.

== Траки

Вторая составляющая - траки.

https://www.kant.ru/articles/1659287/

Траки крепятся к деке и позволяют маневрировать. Траки бывают разной ширины. Чем больше ширина трака - расстояние между краями, тем больше угол поворота.

Крепление траков к деке бывает двух видов: традиционное (traditional kingpin) и реверсивное (reverse kingpin). Различаются они креплением центральной гайки. Крепление гайки в традиционном креплении гайка направлена внутрь крепления, а в ревеосивном - наружу. Разделение условное и легче воспринимается на картинках.

Традиционная подвеска более устойчивая, но не подходит для больших скоростей, потому что начинает вихлять, и почти не подходит для маневров, потому что имеет большой радиус поворота. Это скорее скейтовый вид подвески, там он работает гораздо лучше, так как скейту не нужна скорость и повороты всегда можно докрутить.

https://www.vagaboarder.com/truck-skate-normal-kingpin-o-reverse-kingpin/

Лонгобордисты предпочитают реверсивную подвеску. Этот вид даёт и маневренность и скорость, а также могут быть довольно тонко настроены под стиль ездока.

По методу производства траки делятся на: литые, кованые и высокоточные. Литые - самые дешёвые и слабые, высокоточные - супер-элитные из авиационного алюминия, сделанные на станке ЧПУ, а кованые - нечто среднее между двумя другими.

Важную роль в лонгборде играет колёсная база - расстояние между креплениями траков. При одной и той же длине деки, например 40 дюймов, колёсная база может быть 25, 26 или 28 дюймов. Чем меньше колёсная база, тем маневреннее доска, чем больше база, тем доска стабильнее.

Крепления траков к деке тоже бывают разных видов:

- Drop-through - сквозное крепление, в деке делаются дырки и через них крепятся траки. Занижает центр тяжести, даёт устойчивость, снижает нагрузку на ноги. https://justx3m.ru/longbordy/komplekty/longbord-ridex-onyxia-40/
- Top mount - самое простое крепление, когда траки прикручиваются к низу деки.
- Flush mount - то же, что топ маунт, но траки крепятся в небольшой выемке. Чуть больше устойчивость, чуть лучше маневренность и более ровная поверхность крепления.
- Drop down - это больше про форму деки. А вот double drop - это когда и дека ступенькой и траки крепятся насквозь.

== Колёса или бушинги

То, что делает лонгборд лонгбордом.

Главный параметр колёс - жёсткость. Изменить её - самый простой способ изменить ощущения от катания. Берёшь более мягкие колёса, становится комфортнее, но снижается скорость. Берёшь колёса твёрже, едешь как угорелый, но чувствуешь каждый бугорок дороги. Жёсткость колёс лонгборда измеряется по шкале от 1 до 100. Степень жёсткости большинства производимых колёс - 73-95 баллов, но все они рано или поздно стачиваются. Мягкие - рано, жёсткие - поздно. А твердые могут ещё и расколоться.

https://justx3m.ru/longbordy/kolesa/

Мягкими считаются колёса с жёсткостью 75-87. Самые комфортные для езды и предоставляют лучше сцепление с дорогой. Для простых покатушек.

Жёсткость 88-95 считается средней. Самое то для выполнения маневров и техничного катания.

Самая жесть - это 96-99. Требуют идеально ровной дороги, дают максимальную скорость и лучше подходят для даунхилла и других скоростных стилей катания.

https://z-boardshop.ru/collection/kolesa

Кроме жёсткости важен диаметр колеса. Чем меньше диаметр, тем меньше скорость, но больше ускорение. При увеличении диаметра скорость увеличивается, но её становиться тяжелее набрать.

Средний диаметр колёс лонгборда: от 70 до 80 мм. Всё что меньше подходит для точных стилей катания, когда важны техника и маневренность.

Всё что больше этого порога подходит для фанатов скорости и даунхилла.

И последний параметр колёс - это форма. Бывают бочонки с ровными краями, а бывают со скруглёнными краями. Как обычно, первые хороши для плавной езды, вторые для даунхилла. У бочонков максимально большое пятно контакта с дорогой, это позволяет лучше держать направление. В целом, чем больше пятно контакта, тем устойчивее колёса, но хуже разгон. Пятно контакта меньше, разгон лучше, устойчивость меньше.

https://www.skatepro.ru/c220.htm

== Подшипники

Последний элемент лонгборда - подшипники. Последний отнюдь не по значимости, подшипники отвечают за скорость и лёгкость качения. Для оценки подшипников применяется шкала ABEC (Американский Инженерной Комитет по Подшипникам). Оценка может быть от 1 до 9 баллов, но используются только нечётные: 1, 3, 5, 7, 9. Чем выше оценка по шкале, тем точнее подшипники и тем быстрее,  легче и дольше будут крутиться колёса. Обычные подшипники имеют оценку в 3-5 баллов, подшипники с оценкой ABEC 7-9 настолько круты, что используются в основном для даунхилла.

https://justx3m.ru/longbordy/podshipniki/

Есть и дополнительные компоненты:

- "шкурка" - лента, которая клеится на деку и не позволяет ногам скользить
- разного вида проставки между траками и декой, увеличивающие "клиренс"
- снаряжение ездока, обеспечивающее безопасность
- и т.п.

Дополнительные компоненты не так важны и не сильно влияют на качество катания, поэтому с вашего позволения я не стану про них рассказывать. Расскажу лучше про свой лонгборд.

== Личный опыт

Раньше я ездил на велосипеде и мне это казалось очень крутым и удобным способом передвижения, пока я не попал в ДТП с Газелью, провёл много времени в больнице с сотрясением. Велик после этого случая был "потрачен", как говорится.

В 2017 я решил купить более элегантное средство передвижения, я думал о скейте, но случайно узнал о лонгбордах. Начал смотреть предложения в интернете, но всё, что было доступно казалось слишком дорогим и не аутентичным. Было принято решение покупать за границей и не где-то, а в штатах. Смотрел предложения на ebay, но в итоге купил на сайте Westridge Outdoors за 60$.

Я ничего не знал о лонгбордах, поэтому выбрал "красивенький и не слишком маленький": 44 дюйма, фиштейл, цвета морской волны и дерева, минималистичный и красивый. Просто круизер, просто для покатушек.

https://retrospec.com/products/zed-44-inch-longboard?_pos=3&_sid=85013e7b3&_ss=r

Полные параметры:

* Дека 44 дюйма
* Колёса жёсткостью 85A
* Траки с реверсивным креплением (reverse kingpin)
* Подшипники ABEC-7

В целом впечатления от доски приятные. Стоять научился быстро, ездить довольно легко. Сначала я ещё закупил шлем, перчатки и наколенники, но в полном снаряжении ездить неудобно. Шлем слегка ограничивает видимость да и голова потеет, наколенники были какие-то уродские, из Петровича, я так и не научился их использовать, потому что они спадали, оставил только перчатки.

Носить лонгборд с собой тяжело. Доска весит примерно 3,5 килограмма и неплохие размеры. С одной стороны это недостаток, доска меньшего размера была бы мобильнее, но с другой стороны на такой доске не поедешь там, где не положено, например, в метро или на пешеходных переходах.

Лонгборд - более медленное средство передвижения в сравнении с велосипедом, зато шансов убиться гораздо меньше. Катаясь на логборде, я научился отличать виды асфальта только одним взглядом. Самый любимый асфальт - чёрный. Это новый асфальт и он обычно укладывается без лишних неровностей. Он очень гладкий, ехать по нему можно практически без усилий, особsй кайф - это катиться по нему с горки.

Мощёная тротуарная плитка - тоже отличная поверхность, но слишком скользкая и твёрдая. Я её боюсь. Если упасть на ней, можно расколоть череп как орешек. На асфальте хоть только половину сотрёшь.

== Итог

Лонгборд - отличное средство мобильности. Это лучше, чем быть просто пешеходом, но не так круто, как быть велосипедистом. Лонгборд подарит вам массу новых эмоций, ободранные локти и колени, но вы не пожалеете о содеянной покупке.
